; Auto-generated by the GDDL compiler (Z80 / z88dk-z80asm). Do not edit by hand.
; Scope: scalar (u8/u16), identifier-typed, and string N leaf fields, AoS only.
; --z80-pointer-table=on (§16.2)

; --- type: Villager (AoS instance data) ---
Villager_Sizeof equ 12
Villager_Instances:
Villager_Grubnik:
	db "Grübnik", 0, 0, 0, 0	; name

; --- type: Villager registry (dense declaration-order index, no stable ID) ---
Villager_Registry_Count equ 1
Villager_Grubnik_Index equ 0
Villager_Registry:
	dw Villager_Grubnik

Villager_Find:
	ld l, a
	ld h, 0
	add hl, hl
	ld de, Villager_Registry
	add hl, de
	ld a, (hl)
	inc hl
	ld h, (hl)
	ld l, a
	ret
