; Auto-generated by the GDDL compiler (Z80 / z88dk-z80asm). Do not edit by hand.
; First-pass scope: scalar (u8/u16) and identifier-typed leaf fields, AoS only.
; --z80-pointer-table=on (§16.2)

; --- domain: ActionAttack (indexed form, width u8) ---
ActionAttack_melee_weapon equ 0
ActionAttack_ranged_weapon equ 1

ActionAttack_JumpTable:
	dw ActionAttack_melee_weapon_Handler
	dw ActionAttack_ranged_weapon_Handler

ActionAttack_Dispatch:
	ld l, a
	ld h, 0
	add hl, hl
	ld de, ActionAttack_JumpTable
	add hl, de
	ld a, (hl)
	inc hl
	ld h, (hl)
	ld l, a
	jp (hl)

; --- type: Creature (AoS instance data) ---
Creature_Sizeof equ 2
Creature_Instances:
Creature_Goblin:
	db 10	; hp
	db ActionAttack_melee_weapon	; attack
Creature_Archer:
	db 8	; hp
	db ActionAttack_ranged_weapon	; attack

; --- type: Creature registry (dense declaration-order index, no stable ID) ---
Creature_Registry_Count equ 2
Creature_Goblin_Index equ 0
Creature_Archer_Index equ 1
Creature_Registry:
	dw Creature_Goblin
	dw Creature_Archer

Creature_Find:
	ld l, a
	ld h, 0
	add hl, hl
	ld de, Creature_Registry
	add hl, de
	ld a, (hl)
	inc hl
	ld h, (hl)
	ld l, a
	ret
