; Auto-generated by the GDDL compiler (Z80 / SjASMPlus). Do not edit by hand.
; First-pass scope: scalar (u8/u16) and identifier-typed leaf fields, AoS only.
; --z80-pointer-table=on (§16.2)

; --- type: Character (AoS instance data) ---
Character_Sizeof equ 8
Character_Instances:
Character_Hero:
	dw 60000	; stats_hp
	dw 12000	; stats_mp
	dw 500	; equipment_weapon_power
	dw 42	; level

; --- type: Character registry (dense declaration-order index, no stable ID) ---
Character_Registry_Count equ 1
Character_Hero_Index equ 0
Character_Registry:
	dw Character_Hero

Character_Find:
	ld l, a
	ld h, 0
	add hl, hl
	ld de, Character_Registry
	add hl, de
	ld a, (hl)
	inc hl
	ld h, (hl)
	ld l, a
	ret
