/* Auto-generated by the GDDL compiler (Z80 / z88dk C mode). Do not edit by hand. */
/* Definitions -- C89, targeting zsdcc. Compile with: zcc +<target> -compiler=sdcc ... */
/* --z80-pointer-table=on (SPEC S16.2) */

#include "gddl_z80_export.h"

/* --- type: Villager instance data (AoS) --- */
const Villager Villager_Instances[Villager_Registry_Count] = {
    { "Grübnik" },   /* [0] Grubnik */
};

const Villager *const Villager_Registry[Villager_Registry_Count] = {
    &Villager_Instances[Villager_Grubnik_Index],   /* Grubnik */
};

const Villager *Villager_Find(unsigned char index)
{
    return Villager_Registry[index];
}

