/* Auto-generated by the GDDL compiler (Z80 / z88dk C mode). Do not edit by hand. */
/* Definitions -- C89, targeting zsdcc. Compile with: zcc +<target> -compiler=sdcc ... */
/* --layout=soa -- one array per leaf field, no struct, no {Type}_Find (SPEC S13.4/S13.7): the same dense index that finds an AoS instance already indexes every field array directly. */

#include "gddl_z80_export.h"

/* --- type: Enemy (SoA field arrays) --- */
const unsigned char Enemy_damage_min_max[1][2] = { { 10, 30 } };
const unsigned char Enemy_grid[1][2][3] = { { { 1, 2, 3 }, { 4, 5, 6 } } };
const char Enemy_names[1][2][8] = { { "Al", "Bo" } };
