/* Auto-generated by the GDDL compiler (Z80 / z88dk C mode). Do not edit by hand. */
/* Header: declarations only -- C89, targeting zsdcc. Compile with: zcc +<target> -compiler=sdcc ... */
/* --layout=soa -- one array per leaf field, no struct, no {Type}_Find (SPEC S13.4/S13.7): the same dense index that finds an AoS instance already indexes every field array directly. */

#ifndef GDDL_Z80_EXPORT_H
#define GDDL_Z80_EXPORT_H

/* --- type: Enemy (SoA field arrays) --- */
#define Enemy_Goblin_Index 0

extern const unsigned char Enemy_damage_min_max[1][2];
extern const unsigned char Enemy_grid[1][2][3];
extern const char Enemy_names[1][2][8];

#endif /* GDDL_Z80_EXPORT_H */
