/* Auto-generated by the GDDL compiler (Z80 / z88dk C mode). Do not edit by hand. */
/* Header: declarations only -- C89, targeting zsdcc. Compile with: zcc +<target> -compiler=sdcc ... */
/* --z80-pointer-table=on (SPEC S16.2) */

#ifndef GDDL_Z80_EXPORT_H
#define GDDL_Z80_EXPORT_H

/* --- type: Villager (AoS, sizeof == 12) --- */
typedef struct {
    char name[12];
} Villager;

#define Villager_Registry_Count 1
#define Villager_Grubnik_Index 0

extern const Villager Villager_Instances[Villager_Registry_Count];
extern const Villager *const Villager_Registry[Villager_Registry_Count];
const Villager *Villager_Find(unsigned char index);

#endif /* GDDL_Z80_EXPORT_H */
