#ifndef GDDL_GENERATED_H
#define GDDL_GENERATED_H

// Auto-generated by the GDDL compiler. Do not edit by hand.

#include <cstdint>
#include <array>
#include <string_view>

namespace GDDL
{

enum class ActionAttack : uint64_t
{
    melee_weapon = 0x5c96a731d7d47e03ULL,
    ranged_weapon = 0xaa92e2b5323e5154ULL,
};

enum class ActionAttack_Indexed : uint8_t
{
    melee_weapon = 0,
    ranged_weapon = 1,
};

enum class Element : uint64_t
{
    fire = 0x9bcf40f6874d9103ULL,
    ice = 0x8304148e0f4f19acULL,
    lightning = 0x2ac1c587b5474f2dULL,
    poison = 0xfa09e3b805721ebfULL,
};

struct Object
{
    uint32_t something1;
    uint32_t something2;
};

struct Item
{
    Object object;
    uint32_t weight;
    Element element;
    char name[16];
    ActionAttack_Indexed fast_dispatch;
};

namespace Object_Instances
{
    inline constexpr Object DefaultObject = { 0, 0 };
    inline constexpr Object HeavyObject = { 100, 50 };
    inline constexpr Object LightObject = { 5, 50 };
    inline constexpr Object BaseObject = { 10, 20 };
    inline constexpr Object RealObjectGen1 = { 1, 2 };
    inline constexpr Object RealObjectGen2 = { 10, 2 };
}

namespace Object_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        const Object* data;
    };

    inline constexpr std::array<Entry, 6> Table =
    {
        Entry{ 0x4e4417bdfce7a91aULL, "HeavyObject", &Object_Instances::HeavyObject },
        Entry{ 0xad84053e592e7248ULL, "DefaultObject", &Object_Instances::DefaultObject },
        Entry{ 0xea3fb911673e5dc9ULL, "LightObject", &Object_Instances::LightObject },
        Entry{ 0xed9105d6ab5f2814ULL, "RealObjectGen1", &Object_Instances::RealObjectGen1 },
        Entry{ 0xed9108d6ab5f2d2dULL, "RealObjectGen2", &Object_Instances::RealObjectGen2 },
        Entry{ 0xf334fa27c5ce1648ULL, "BaseObject", &Object_Instances::BaseObject },
    };

    constexpr const Object* Find(uint64_t instance_id)
    {
        std::size_t lo = 0, hi = Table.size();

        while (lo < hi)
        {
            std::size_t mid = lo + (hi - lo) / 2;

            if (Table[mid].instance_id < instance_id)
            {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if (lo < Table.size() && Table[lo].instance_id == instance_id)
        {
            return Table[lo].data;
        }

        return nullptr;
    }

    constexpr const Object* Find(std::string_view name)
    {
        for (const auto& entry : Table)
        {
            if (entry.name == name)
            {
                return entry.data;
            }
        }

        return nullptr;
    }
} // namespace Object_Registry

namespace Item_Instances
{
    inline constexpr Item ItemViaFullReplace = { Object{ 10, 20 }, 5, Element::fire, "Sword", ActionAttack_Indexed::melee_weapon };
    inline constexpr Item ItemViaBareModify = { Object{ 99, 100 }, 7, Element::ice, "AAAAAAAAAAAAAAA", ActionAttack_Indexed::ranged_weapon };
    inline constexpr Item ItemCopy = { Object{ 10, 20 }, 50, Element::lightning, "Shield", ActionAttack_Indexed::melee_weapon };
}

namespace Item_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        const Item* data;
    };

    inline constexpr std::array<Entry, 3> Table =
    {
        Entry{ 0x8ad19844df88b655ULL, "ItemViaBareModify", &Item_Instances::ItemViaBareModify },
        Entry{ 0xb1ea277c9f6610e8ULL, "ItemCopy", &Item_Instances::ItemCopy },
        Entry{ 0xf1112704e607b426ULL, "ItemViaFullReplace", &Item_Instances::ItemViaFullReplace },
    };

    constexpr const Item* Find(uint64_t instance_id)
    {
        std::size_t lo = 0, hi = Table.size();

        while (lo < hi)
        {
            std::size_t mid = lo + (hi - lo) / 2;

            if (Table[mid].instance_id < instance_id)
            {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if (lo < Table.size() && Table[lo].instance_id == instance_id)
        {
            return Table[lo].data;
        }

        return nullptr;
    }

    constexpr const Item* Find(std::string_view name)
    {
        for (const auto& entry : Table)
        {
            if (entry.name == name)
            {
                return entry.data;
            }
        }

        return nullptr;
    }
} // namespace Item_Registry

// §17.5: compile-time schema table, for comparison against
// whatever a loaded .gddldata.bin/.gddlmeta.json pair claims at
// runtime (§17.6). schema_hash/record_size here are computed by
// the EXACT SAME functions the .gddldata.bin exporter calls --
// see export_cpp.py's compute_schema_hash/compute_record_size,
// shared with export_binary.py, never a second implementation.
struct SchemaEntry
{
    std::string_view type_name;
    uint64_t schema_hash;
    uint32_t record_size;
};

inline constexpr std::array<SchemaEntry, 2> SchemaTable =
{
    SchemaEntry{ "Object", 0xc3b65b8d9dc943b8ULL, 8 },
    SchemaEntry{ "Item", 0x2c99385395d2d57eULL, 37 },
};

} // namespace GDDL

#endif // GDDL_GENERATED_H
