# Part of GDDL, licensed under the GDDL License v1.0.
# See LICENSE at the project root for full terms.

"""
Validates §17.5's C++ compile-time schema table by DIRECT COMPARISON
against export_binary.py's own .gddlmeta.json output for the same
fixture -- not by eye, not by re-deriving expected values by hand.

This is the one test that actually proves the "generated by the same
code path, can never drift apart by construction" claim is true rather
than merely structurally plausible: parses the (type_name, schema_hash,
record_size) tuples straight out of the generated C++ source text, and
asserts they're identical to what export_binary.py independently wrote
into the manifest for the same types from the same source.

Also does a real g++17 compile of the emitted table to confirm it's
valid, well-formed C++ -- not just text that looks right.

Run directly: python3 export_binary_test/test_schema_table_cpp.py
"""

import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

# Same fix as test_binary_export.py's sibling script -- three
# directories up from compiler-python/tests/export_binary_test/ reaches
# compiler-python/, then into gddl/.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from gddl.parser import parse_file
from gddl.resolve import resolve_all
from gddl.export_cpp import generate_header, generate_split
from gddl.export_binary import export_binary


FIXTURE = os.path.join(os.path.dirname(__file__), "export_test_binary_coverage.gddl")

_ENTRY_RE = re.compile(
    r'SchemaEntry\{\s*"([^"]+)",\s*(0x[0-9a-fA-F]+)ULL,\s*(\d+)\s*\}')


def parse_schema_table_from_cpp(header_text: str):
    """Extracts {type_name: (schema_hash_int, record_size_int)} directly
    from the generated C++ source text -- a real text-level parse of
    what was actually emitted, not a re-derivation from the IR."""
    result = {}
    for m in _ENTRY_RE.finditer(header_text):
        name, hash_hex, size_str = m.groups()
        result[name] = (int(hash_hex, 16), int(size_str))
    return result


def get_binary_export_schema(build_dir):
    """Runs export_binary.py's own exporter for the same fixture/types
    and returns {type_name: (schema_hash_int, record_size_int)} parsed
    straight out of its .gddlmeta.json -- the independent ground truth
    this test compares the C++ table against."""
    prog = parse_file(FIXTURE)
    resolver = resolve_all(prog)
    out_stem = os.path.join(build_dir, "binary_ref")
    export_binary(resolver.reg, resolver, ["Item", "Object"], out_stem)
    with open(out_stem + ".gddlmeta.json") as f:
        manifest = json.load(f)
    return {t["name"]: (int(t["schema_hash"], 16), t["record_size"])
            for t in manifest["types"]}


def check_direct_comparison(cpp_schema, binary_schema):
    print("=== Check: C++ table vs export_binary.py, direct comparison ===")
    # The C++ table covers EVERY type in the schema (§17.5's own
    # wording), which for this fixture is exactly {Item, Object} -- the
    # same two types export_binary.py was asked to serialize. Confirm
    # the sets match before comparing values, so a silently-missing or
    # silently-extra entry can't hide behind a per-key loop that only
    # checks what's already expected to be there.
    assert set(cpp_schema) == set(binary_schema), \
        f"type set mismatch: C++ has {set(cpp_schema)}, binary has {set(binary_schema)}"

    for name in sorted(cpp_schema):
        cpp_hash, cpp_size = cpp_schema[name]
        bin_hash, bin_size = binary_schema[name]
        assert cpp_hash == bin_hash, \
            f"{name}: C++ schema_hash {cpp_hash:016x} != " \
            f"export_binary.py schema_hash {bin_hash:016x}"
        assert cpp_size == bin_size, \
            f"{name}: C++ record_size {cpp_size} != " \
            f"export_binary.py record_size {bin_size}"
        print(f"  {name}: hash {cpp_hash:016x}, size {cpp_size} -- "
              f"C++ and export_binary.py agree exactly")
    print("PASSED: every (type_name, schema_hash, record_size) triple "
          "is byte-identical between the C++ table and export_binary.py's "
          "own output for the same fixture.\n")


def check_real_compile(header_text, build_dir, label):
    """Real g++17 compile of the emitted table -- confirms it's valid,
    well-formed C++, not just text that happens to look right."""
    print(f"=== Check: real g++17 compile ({label}) ===")
    header_path = os.path.join(build_dir, f"{label}.h")
    with open(header_path, "w") as f:
        f.write(header_text)

    cpp_path = os.path.join(build_dir, f"{label}_main.cpp")
    with open(cpp_path, "w") as f:
        f.write(f'''#include "{label}.h"
#include <cstdio>
int main() {{
    static_assert(GDDL::SchemaTable.size() == 2);
    for (const auto& e : GDDL::SchemaTable) {{
        std::printf("%.*s: hash=%016llx size=%u\\n",
                     (int)e.type_name.size(), e.type_name.data(),
                     (unsigned long long)e.schema_hash, e.record_size);
    }}
    return 0;
}}
''')

    binary_path = os.path.join(build_dir, f"{label}_bin")
    result = subprocess.run(
        ["g++", "-std=c++17", "-Wall", "-Wextra", "-I", build_dir,
         cpp_path, "-o", binary_path],
        capture_output=True, text=True)
    if result.returncode != 0:
        print(result.stdout)
        print(result.stderr)
        raise AssertionError(f"g++17 compile FAILED for {label}")

    run_result = subprocess.run([binary_path], capture_output=True, text=True)
    assert run_result.returncode == 0, f"{label} binary exited nonzero"
    print(run_result.stdout)
    print(f"PASSED: {label} compiles and runs cleanly under real g++17.\n")


def main():
    build_dir = tempfile.mkdtemp(prefix="gddl_schema_table_test_")
    try:
        prog = parse_file(FIXTURE)
        resolver = resolve_all(prog)
        reg = resolver.reg

        # Single-header mode
        header_single = generate_header(reg, resolver)
        cpp_schema_single = parse_schema_table_from_cpp(header_single)

        # Split mode -- table lives in the .h, not the .cpp (see
        # render_schema_table's own docstring for why)
        header_split, _cpp_split = generate_split(
            reg, resolver, header_filename="split_test.h")
        cpp_schema_split = parse_schema_table_from_cpp(header_split)

        binary_schema = get_binary_export_schema(build_dir)

        print(f"export_binary.py's own manifest: {binary_schema}\n")

        check_direct_comparison(cpp_schema_single, binary_schema)
        check_direct_comparison(cpp_schema_split, binary_schema)

        # Confirm single-header and split modes produce the SAME table
        # values as each other too (both call the exact same
        # render_schema_table -- this is a sanity check on that, not a
        # new independent claim).
        assert cpp_schema_single == cpp_schema_split, \
            "single-header and split modes produced DIFFERENT schema " \
            "table values for the same fixture -- should be impossible, " \
            "both call render_schema_table identically"
        print("Single-header and split modes agree with each other too "
              f"(both call render_schema_table the same way): {cpp_schema_single}\n")

        check_real_compile(header_single, build_dir, "single_header")
        check_real_compile(header_split, build_dir, "split")

        print("ALL CHECKS PASSED.")
    finally:
        shutil.rmtree(build_dir, ignore_errors=True)


if __name__ == "__main__":
    main()
