// Auto-generated by the GDDL compiler. Do not edit by hand.

#include "generated_schema_table_split.h"

namespace GDDL
{

namespace Object_Instances
{
    const Object DefaultObject = { 0, 0 };
    const Object HeavyObject = { 100, 50 };
    const Object LightObject = { 5, 50 };
    const Object BaseObject = { 10, 20 };
    const Object RealObjectGen1 = { 1, 2 };
    const Object RealObjectGen2 = { 10, 2 };
} // namespace Object_Instances

namespace Object_Registry
{
    const std::array<Entry, 6> Table =
    {
        Entry{ 0x4e4417bdfce7a91aULL, "HeavyObject", &Object_Instances::HeavyObject },
        Entry{ 0xad84053e592e7248ULL, "DefaultObject", &Object_Instances::DefaultObject },
        Entry{ 0xea3fb911673e5dc9ULL, "LightObject", &Object_Instances::LightObject },
        Entry{ 0xed9105d6ab5f2814ULL, "RealObjectGen1", &Object_Instances::RealObjectGen1 },
        Entry{ 0xed9108d6ab5f2d2dULL, "RealObjectGen2", &Object_Instances::RealObjectGen2 },
        Entry{ 0xf334fa27c5ce1648ULL, "BaseObject", &Object_Instances::BaseObject },
    };

    const Object* Find(uint64_t instance_id)
    {
        std::size_t lo = 0, hi = Table.size();

        while (lo < hi)
        {
            std::size_t mid = lo + (hi - lo) / 2;

            if (Table[mid].instance_id < instance_id)
            {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if (lo < Table.size() && Table[lo].instance_id == instance_id)
        {
            return Table[lo].data;
        }

        return nullptr;
    }

    const Object* Find(std::string_view name)
    {
        for (const auto& entry : Table)
        {
            if (entry.name == name)
            {
                return entry.data;
            }
        }

        return nullptr;
    }
} // namespace Object_Registry

namespace Item_Instances
{
    const Item ItemViaFullReplace = { Object{ 10, 20 }, 5, Element::fire, "Sword", ActionAttack_Indexed::melee_weapon };
    const Item ItemViaBareModify = { Object{ 99, 100 }, 7, Element::ice, "AAAAAAAAAAAAAAA", ActionAttack_Indexed::ranged_weapon };
    const Item ItemCopy = { Object{ 10, 20 }, 50, Element::lightning, "Shield", ActionAttack_Indexed::melee_weapon };
} // namespace Item_Instances

namespace Item_Registry
{
    const std::array<Entry, 3> Table =
    {
        Entry{ 0x8ad19844df88b655ULL, "ItemViaBareModify", &Item_Instances::ItemViaBareModify },
        Entry{ 0xb1ea277c9f6610e8ULL, "ItemCopy", &Item_Instances::ItemCopy },
        Entry{ 0xf1112704e607b426ULL, "ItemViaFullReplace", &Item_Instances::ItemViaFullReplace },
    };

    const Item* Find(uint64_t instance_id)
    {
        std::size_t lo = 0, hi = Table.size();

        while (lo < hi)
        {
            std::size_t mid = lo + (hi - lo) / 2;

            if (Table[mid].instance_id < instance_id)
            {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if (lo < Table.size() && Table[lo].instance_id == instance_id)
        {
            return Table[lo].data;
        }

        return nullptr;
    }

    const Item* Find(std::string_view name)
    {
        for (const auto& entry : Table)
        {
            if (entry.name == name)
            {
                return entry.data;
            }
        }

        return nullptr;
    }
} // namespace Item_Registry
} // namespace GDDL
