#ifndef GDDL_GENERATED_68000_H
#define GDDL_GENERATED_68000_H

/* Auto-generated by the GDDL compiler (68000 / vbcc, C89). Do not edit by hand. */

/* --- domain: Rarity (dense index, width u8) --- */
typedef unsigned char Rarity;
#define Rarity_common ((Rarity)0)
#define Rarity_rare ((Rarity)1)
#define Rarity_epic ((Rarity)2)

/* --- type: Item --- */
typedef struct Item
{
    unsigned char power;
} Item;

/* --- type: Item instances --- */
#define Item_BasicSword_Index 0

extern const Item Item_Instances[1];

const Item* Item_Find(unsigned int index);

#endif /* GDDL_GENERATED_68000_H */
