/* Auto-generated by the GDDL compiler (68000 / vbcc, C89). Do not edit by hand. */

#include "generated_68000.h"

/* --- type: Item instances --- */
const Item Item_Instances[1] =
{
    { 10 },  /* BasicSword */
};

const Item* Item_Find(unsigned int index)
{
    return &Item_Instances[index];
}
