#ifndef GDDL_GENERATED_H
#define GDDL_GENERATED_H

// Auto-generated by the GDDL compiler. Do not edit by hand.

#include <cstdint>
#include <array>
#include <string_view>

namespace GDDL
{

enum class Rarity : uint64_t
{
    common = 0x08977013dc250161ULL,
    rare = 0x244ea920a683ca6aULL,
    epic = 0x0caf9a345881c0c9ULL,
};

enum class Rarity_Indexed : uint8_t
{
    common = 0,
    rare = 1,
    epic = 2,
};

struct Item
{
    uint8_t power;
};

namespace Item_Instances
{
    extern const Item BasicSword;
}

namespace Item_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        const Item* data;
    };

    extern const std::array<Entry, 1> Table;

    const Item* Find(uint64_t instance_id);

    const Item* Find(std::string_view name);
} // namespace Item_Registry
} // namespace GDDL

#endif // GDDL_GENERATED_H
