#ifndef GDDL_GENERATED_H
#define GDDL_GENERATED_H

// Auto-generated by the GDDL compiler. Do not edit by hand.

#include <cstdint>
#include <array>
#include <string_view>

namespace GDDL
{

enum class Rarity : uint64_t
{
    common = 0x08977013dc250161ULL,
    rare = 0x244ea920a683ca6aULL,
    epic = 0x0caf9a345881c0c9ULL,
};

struct Item
{
    uint8_t power;
};

namespace Item_Instances
{
    inline constexpr Item BasicSword = { 10 };
}

namespace Item_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        const Item* data;
    };

    inline constexpr std::array<Entry, 1> Table =
    {
        Entry{ 0x50632af66a000c59ULL, "BasicSword", &Item_Instances::BasicSword },
    };

    constexpr const Item* Find(uint64_t instance_id)
    {
        std::size_t lo = 0, hi = Table.size();

        while (lo < hi)
        {
            std::size_t mid = lo + (hi - lo) / 2;

            if (Table[mid].instance_id < instance_id)
            {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if (lo < Table.size() && Table[lo].instance_id == instance_id)
        {
            return Table[lo].data;
        }

        return nullptr;
    }

    constexpr const Item* Find(std::string_view name)
    {
        for (const auto& entry : Table)
        {
            if (entry.name == name)
            {
                return entry.data;
            }
        }

        return nullptr;
    }
} // namespace Item_Registry
} // namespace GDDL

#endif // GDDL_GENERATED_H
