; Auto-generated by the GDDL compiler (Z80 / SjASMPlus). Do not edit by hand.
; Scope: scalar (u8/u16), identifier-typed, and string N leaf fields, AoS only.
; --z80-pointer-table=on (§16.2)

; --- domain: Rarity (indexed form, width u8) ---
Rarity_common equ 0
Rarity_rare equ 1
Rarity_epic equ 2

Rarity_JumpTable:
	dw Rarity_common_Handler
	dw Rarity_rare_Handler
	dw Rarity_epic_Handler

Rarity_Dispatch:
	ld l, a
	ld h, 0
	add hl, hl
	ld de, Rarity_JumpTable
	add hl, de
	ld a, (hl)
	inc hl
	ld h, (hl)
	ld l, a
	jp (hl)

; --- type: Item (AoS instance data) ---
Item_Sizeof equ 1
Item_Instances:
Item_BasicSword:
	db 10	; power

; --- type: Item registry (dense declaration-order index, no stable ID) ---
Item_Registry_Count equ 1
Item_BasicSword_Index equ 0
Item_Registry:
	dw Item_BasicSword

Item_Find:
	ld l, a
	ld h, 0
	add hl, hl
	ld de, Item_Registry
	add hl, de
	ld a, (hl)
	inc hl
	ld h, (hl)
	ld l, a
	ret
