#ifndef GDDL_GENERATED_H
#define GDDL_GENERATED_H

// Auto-generated by the GDDL compiler. Do not edit by hand.

#include <cstdint>
#include <array>
#include <string_view>

namespace GDDL
{

enum class Rarity : uint64_t
{
    common = 0x08977013dc250161ULL, // Common tier
    rare   = 0x244ea920a683ca6aULL, // Rare tier
    epic   = 0x0caf9a345881c0c9ULL, // Epic tier
};

struct Item
{
    uint8_t power;
};

namespace Item_Instances
{
    extern const Item BasicSword;
}

namespace Item_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        const Item* data;
    };

    extern const std::array<Entry, 1> Table;

    const Item* Find(uint64_t instance_id);

    const Item* Find(std::string_view name);
} // namespace Item_Registry

// §17.5: compile-time schema table, for comparison against
// whatever a loaded .gddldata.bin/.gddlmeta.json pair claims at
// runtime (§17.6). schema_hash/record_size here are computed by
// the EXACT SAME functions the .gddldata.bin exporter calls --
// see export_cpp.py's compute_schema_hash/compute_record_size,
// shared with export_binary.py, never a second implementation.
struct SchemaEntry
{
    std::string_view type_name;
    uint64_t schema_hash;
    uint32_t record_size;
};

inline constexpr std::array<SchemaEntry, 1> SchemaTable =
{
    SchemaEntry{ "Item", 0xb15c717ddff36dd6ULL, 1 },
};

} // namespace GDDL

#endif // GDDL_GENERATED_H
