/* Auto-generated by the GDDL compiler (Z80 / z88dk C mode). Do not edit by hand. */
/* Header: declarations only -- C89, targeting zsdcc. Compile with: zcc +<target> -compiler=sdcc ... */
/* --layout=soa -- one array per leaf field, no struct, no {Type}_Find (SPEC S13.4/S13.7): the same dense index that finds an AoS instance already indexes every field array directly. */

#ifndef GDDL_Z80_EXPORT_H
#define GDDL_Z80_EXPORT_H

/* --- domain: Rarity (indexed form, width u8) --- */
#define Rarity_common 0
#define Rarity_rare 1
#define Rarity_Count 2

/* --- type: Item (SoA field arrays) --- */
#define Item_Sword_Index 0
#define Item_Bow_Index 1
#define Item_Shield_Index 2

extern const unsigned int Item_power[3];
extern const unsigned char Item_rarity[3];

#endif /* GDDL_Z80_EXPORT_H */
