/* Auto-generated by the GDDL compiler (Z80 / z88dk C mode). Do not edit by hand. */
/* Definitions -- C89, targeting zsdcc. Compile with: zcc +<target> -compiler=sdcc ... */
/* --layout=soa -- one array per leaf field, no struct, no {Type}_Find (SPEC S13.4/S13.7): the same dense index that finds an AoS instance already indexes every field array directly. */

#include "gddl_z80_export.h"

/* --- type: Item (SoA field arrays) --- */
const unsigned int Item_power[3] = { 42, 15, 8 };
const unsigned char Item_rarity[3] = { Rarity_rare, Rarity_common, Rarity_common };
