; Auto-generated by the GDDL compiler (6502 / 64tass). Do not edit by hand.
; First-pass scope: scalar (u8/u16) and identifier-typed leaf fields, AoS only.

; --- domain: ActionAttack (indexed form, width u8) ---
ActionAttack_melee_weapon = 0
ActionAttack_ranged_weapon = 1

ActionAttack_JumpTable_Lo:
	.byte <ActionAttack_melee_weapon_Handler
	.byte <ActionAttack_ranged_weapon_Handler
ActionAttack_JumpTable_Hi:
	.byte >ActionAttack_melee_weapon_Handler
	.byte >ActionAttack_ranged_weapon_Handler

ActionAttack_DispatchPtr = $f4

ActionAttack_Dispatch:
	lda ActionAttack_JumpTable_Lo,x
	sta ActionAttack_DispatchPtr
	lda ActionAttack_JumpTable_Hi,x
	sta ActionAttack_DispatchPtr+1
	jmp (ActionAttack_DispatchPtr)

; --- domain: Element (indexed form, width u8) ---
Element_fire = 0
Element_ice = 1
Element_lightning = 2

Element_JumpTable_Lo:
	.byte <Element_fire_Handler
	.byte <Element_ice_Handler
	.byte <Element_lightning_Handler
Element_JumpTable_Hi:
	.byte >Element_fire_Handler
	.byte >Element_ice_Handler
	.byte >Element_lightning_Handler

Element_DispatchPtr = $f6

Element_Dispatch:
	lda Element_JumpTable_Lo,x
	sta Element_DispatchPtr
	lda Element_JumpTable_Hi,x
	sta Element_DispatchPtr+1
	jmp (Element_DispatchPtr)

; --- type: Creature (AoS instance data) ---
Creature_Goblin:
	.byte 10	; hp
	.byte ActionAttack_melee_weapon	; attack
Creature_Archer:
	.byte 8	; hp
	.byte ActionAttack_ranged_weapon	; attack

; --- type: Item (AoS instance data) ---
Item_Sword:
	.byte 5	; object_something1
	.byte 3	; object_something2
	.byte 7	; weight
	.byte Element_fire	; element
Item_Shield:
	.byte 2	; object_something1
	.byte 9	; object_something2
	.byte 4	; weight
	.byte Element_ice	; element

; --- type: Creature registry (dense declaration-order index, no stable ID) ---
Creature_Registry_Count = 2
Creature_Goblin_Index = 0
Creature_Archer_Index = 1
Creature_Registry_Lo:
	.byte <Creature_Goblin
	.byte <Creature_Archer
Creature_Registry_Hi:
	.byte >Creature_Goblin
	.byte >Creature_Archer

Creature_RegistryPtr = $f0

Creature_Find:
	lda Creature_Registry_Lo,x
	sta Creature_RegistryPtr
	lda Creature_Registry_Hi,x
	sta Creature_RegistryPtr+1
	rts

; --- type: Item registry (dense declaration-order index, no stable ID) ---
Item_Registry_Count = 2
Item_Sword_Index = 0
Item_Shield_Index = 1
Item_Registry_Lo:
	.byte <Item_Sword
	.byte <Item_Shield
Item_Registry_Hi:
	.byte >Item_Sword
	.byte >Item_Shield

Item_RegistryPtr = $f2

Item_Find:
	lda Item_Registry_Lo,x
	sta Item_RegistryPtr
	lda Item_Registry_Hi,x
	sta Item_RegistryPtr+1
	rts
