; Auto-generated by the GDDL compiler (6502 / ACME). Do not edit by hand.
; Scope: scalar (u8/u16), identifier-typed, and string N leaf fields, AoS only.

; --- type: Villager (AoS instance data) ---
Villager_Grubnik:
	!text "Grübnik"	; name
	!byte 0, 0, 0, 0

; --- type: Villager registry (dense declaration-order index, no stable ID) ---
Villager_Registry_Count = 1
Villager_Grubnik_Index = 0
Villager_Registry_Lo:
	!byte <Villager_Grubnik
Villager_Registry_Hi:
	!byte >Villager_Grubnik

Villager_RegistryPtr = $02

Villager_Find:
	LDA Villager_Registry_Lo,X
	STA Villager_RegistryPtr
	LDA Villager_Registry_Hi,X
	STA Villager_RegistryPtr+1
	RTS
