// Auto-generated by the GDDL compiler (6502 / KickAssembler). Do not edit by hand.
.encoding "ascii"
// Scope: scalar (u8/u16), identifier-typed, and string N leaf fields, AoS only.

// --- type: Villager (AoS instance data) ---
Villager_Grubnik:
	.text "Gr"	// name
	.byte $c3
	.byte $bc
	.text "bnik"
	.byte 0, 0, 0, 0

// --- type: Villager registry (dense declaration-order index, no stable ID) ---
.label Villager_Registry_Count = 1
.label Villager_Grubnik_Index = 0
Villager_Registry_Lo:
	.byte <Villager_Grubnik
Villager_Registry_Hi:
	.byte >Villager_Grubnik

.label Villager_RegistryPtr = $02

Villager_Find:
	lda Villager_Registry_Lo,x
	sta Villager_RegistryPtr
	lda Villager_Registry_Hi,x
	sta Villager_RegistryPtr+1
	rts
