; Auto-generated by the GDDL compiler (6502 / 64tass). Do not edit by hand.
; First-pass scope: scalar (u8/u16) and identifier-typed leaf fields, layout=soa.

; --- domain: ActionAttack (indexed form, width u8) ---
ActionAttack_melee_weapon = 0
ActionAttack_ranged_weapon = 1

ActionAttack_JumpTable_Lo:
	.byte <ActionAttack_melee_weapon_Handler
	.byte <ActionAttack_ranged_weapon_Handler
ActionAttack_JumpTable_Hi:
	.byte >ActionAttack_melee_weapon_Handler
	.byte >ActionAttack_ranged_weapon_Handler

ActionAttack_DispatchPtr = $f0

ActionAttack_Dispatch:
	lda ActionAttack_JumpTable_Lo,x
	sta ActionAttack_DispatchPtr
	lda ActionAttack_JumpTable_Hi,x
	sta ActionAttack_DispatchPtr+1
	jmp (ActionAttack_DispatchPtr)

; --- domain: Element (indexed form, width u8) ---
Element_fire = 0
Element_ice = 1
Element_lightning = 2

Element_JumpTable_Lo:
	.byte <Element_fire_Handler
	.byte <Element_ice_Handler
	.byte <Element_lightning_Handler
Element_JumpTable_Hi:
	.byte >Element_fire_Handler
	.byte >Element_ice_Handler
	.byte >Element_lightning_Handler

Element_DispatchPtr = $f2

Element_Dispatch:
	lda Element_JumpTable_Lo,x
	sta Element_DispatchPtr
	lda Element_JumpTable_Hi,x
	sta Element_DispatchPtr+1
	jmp (Element_DispatchPtr)

; --- type: Creature (SoA field arrays) ---
Creature_Goblin_Index = 0
Creature_Archer_Index = 1
Creature_hp:
	.byte 10
	.byte 8
Creature_attack:
	.byte ActionAttack_melee_weapon
	.byte ActionAttack_ranged_weapon

; --- type: Item (SoA field arrays) ---
Item_Sword_Index = 0
Item_Shield_Index = 1
Item_object_something1:
	.byte 5
	.byte 2
Item_object_something2:
	.byte 3
	.byte 9
Item_weight:
	.byte 7
	.byte 4
Item_element:
	.byte Element_fire
	.byte Element_ice
