/* Auto-generated by the GDDL compiler (68000 / vbcc, C89). Do not edit by hand. */

#include "generated_68000_pools_soa.h"

/* --- type: Enemy (SoA field arrays) --- */
const signed long Enemy_hp[1] = { 1 };
const signed long Enemy_damage_min_max[1][2] = { { 0, 0 } };
const char Enemy_name[1][16] = { "x" };
const signed long Enemy_position_x[1] = { 0 };
const signed long Enemy_position_y[1] = { 0 };

/* --- pool: ActiveEnemies (SoA reservation) --- */
signed long ActiveEnemies_hp[8];
signed long ActiveEnemies_damage_min_max[8][2];
char ActiveEnemies_name[8][16];
signed long ActiveEnemies_position_x[8];
signed long ActiveEnemies_position_y[8];
