#ifndef GDDL_GENERATED_68000_H
#define GDDL_GENERATED_68000_H

/* Auto-generated by the GDDL compiler (68000 / vbcc, C89). Do not edit by hand. */

/* --- type: Vec2 --- */
typedef struct Vec2
{
    signed long x;
    signed long y;
} Vec2;

/* --- type: Enemy --- */
typedef struct Enemy
{
    signed long hp;
    signed long damage_min_max[2];
    char        name[16];
    Vec2        position;
} Enemy;

/* --- type: Enemy instances --- */
#define Enemy_Placeholder_Index 0

extern const Enemy Enemy_Instances[1];

const Enemy* Enemy_Find(unsigned int index);

/* --- pool: ActiveEnemies (Enemy x 8, AoS reservation, uninitialized -- §22.4) --- */
extern Enemy ActiveEnemies[8];

#endif /* GDDL_GENERATED_68000_H */
