/* Auto-generated by the GDDL compiler (68000 / vbcc, C89). Do not edit by hand. */

#include "generated_68000_arrays_soa.h"

/* --- type: Enemy (SoA field arrays) --- */
const signed long Enemy_damage_min_max[2][2] = { { 10, 30 }, { 10, 80 } };
const signed long Enemy_grid[2][2][3] = { { { 1, 2, 3 }, { 4, 5, 6 } }, { { 1, 2, 3 }, { 4, 5, 6 } } };
const char Enemy_names[2][4][16] = { { "Alice", "Bob", "Carol, Jr.", "Dave" }, { "Alice", "Bob", "Carol, Jr.", "Dave" } };
