#ifndef GDDL_GENERATED_68000_H
#define GDDL_GENERATED_68000_H

/* Auto-generated by the GDDL compiler (68000 / vbcc, C89). Do not edit by hand. */

/* --- type: Stats --- */
typedef struct Stats
{
    unsigned short hp;
    unsigned short mp;
} Stats;

/* --- type: Equipment --- */
typedef struct Equipment
{
    unsigned short weapon_power;
} Equipment;

/* --- type: Character --- */
typedef struct Character
{
    Stats stats;
    Equipment equipment;
    unsigned short level;
} Character;

/* --- type: Character instances --- */
#define Character_Hero_Index 0

extern const Character Character_Instances[1];

const Character* Character_Find(unsigned int index);

#endif /* GDDL_GENERATED_68000_H */
