#ifndef GDDL_GENERATED_68000_H
#define GDDL_GENERATED_68000_H

/* Auto-generated by the GDDL compiler (68000 / vbcc, C89). Do not edit by hand. */

/* --- domain: ActionAttack (dense index, width u8) --- */
typedef unsigned char ActionAttack;
#define ActionAttack_melee_weapon ((ActionAttack)0)
#define ActionAttack_ranged_weapon ((ActionAttack)1)

/* --- domain: Element (dense index, width u16) --- */
typedef unsigned short Element;
#define Element_fire ((Element)0)
#define Element_ice ((Element)1)
#define Element_lightning ((Element)2)

/* --- domain: Rarity (dense index, width u32) --- */
typedef unsigned long Rarity;
#define Rarity_common ((Rarity)0)
#define Rarity_rare ((Rarity)1)

/* --- type: Creature (SoA field arrays) --- */
#define Creature_Goblin_Index 0
#define Creature_Archer_Index 1

extern const unsigned char Creature_hp[2];
extern const ActionAttack Creature_attack[2];
extern const Rarity Creature_rarity[2];

/* --- type: Item (SoA field arrays) --- */
#define Item_Sword_Index 0
#define Item_Shield_Index 1

extern const unsigned char Item_object_something1[2];
extern const unsigned char Item_object_something2[2];
extern const unsigned char Item_weight[2];
extern const Element Item_element[2];
extern const char Item_name[2][16];

#endif /* GDDL_GENERATED_68000_H */
