#ifndef GDDL_GENERATED_68000_H
#define GDDL_GENERATED_68000_H

/* Auto-generated by the GDDL compiler (68000 / vbcc, C89). Do not edit by hand. */

/* --- type: Enemy (SoA field arrays) --- */
#define Enemy_BaseGoblin_Index 0
#define Enemy_StrongerGoblin_Index 1

extern const signed long Enemy_damage_min_max[2][2];
extern const signed long Enemy_grid[2][2][3];
extern const char Enemy_names[2][4][16];

#endif /* GDDL_GENERATED_68000_H */
