/* Auto-generated by the GDDL compiler (68000 / vbcc, C89). Do not edit by hand. */

#include "generated_68000_minimal.h"

/* --- type: Creature instances --- */
const Creature Creature_Instances[2] =
{
    { 10, ActionAttack_melee_weapon, Rarity_common },  /* Goblin */
    { 8, ActionAttack_ranged_weapon, Rarity_rare },  /* Archer */
};

const Creature* Creature_Find(unsigned int index)
{
    return &Creature_Instances[index];
}

/* --- type: Item instances --- */
const Item Item_Instances[2] =
{
    { { 5, 3 }, 7, Element_fire, "Sword" },  /* Sword */
    { { 2, 9 }, 4, Element_ice, "Shield" },  /* Shield */
};

const Item* Item_Find(unsigned int index)
{
    return &Item_Instances[index];
}
