#ifndef GDDL_GENERATED_68000_H
#define GDDL_GENERATED_68000_H

/* Auto-generated by the GDDL compiler (68000 / vbcc, C89). Do not edit by hand. */

/* --- domain: ItemRarity (dense index, width u8) --- */
typedef unsigned char ItemRarity;
#define ItemRarity_common ((ItemRarity)0)
#define ItemRarity_rare ((ItemRarity)1)

/* --- type: Object --- */
typedef struct Object
{
    unsigned char weight;
} Object;

/* --- type: Item --- */
typedef struct Item
{
    ItemRarity rarity;
    Object object;
} Item;

/* --- type: Item instances --- */
#define Item_Sword_Index 0

extern const Item Item_Instances[1];

const Item* Item_Find(unsigned int index);

#endif /* GDDL_GENERATED_68000_H */
