/* Auto-generated by the GDDL compiler (68000 / vbcc, C89). Do not edit by hand. */

#include "generated_68000_arrays.h"

/* --- type: Enemy instances --- */
const Enemy Enemy_Instances[2] =
{
    { { 10, 30 }, { { 1, 2, 3 }, { 4, 5, 6 } }, { "Alice", "Bob", "Carol, Jr.", "Dave" } },  /* BaseGoblin */
    { { 10, 80 }, { { 1, 2, 3 }, { 4, 5, 6 } }, { "Alice", "Bob", "Carol, Jr.", "Dave" } },  /* StrongerGoblin */
};

const Enemy* Enemy_Find(unsigned int index)
{
    return &Enemy_Instances[index];
}
