#ifndef GDDL_GENERATED_68000_H
#define GDDL_GENERATED_68000_H

/* Auto-generated by the GDDL compiler (68000 / vbcc, C89). Do not edit by hand. */

/* --- type: Enemy --- */
typedef struct Enemy
{
    signed long damage_min_max[2];
    signed long grid[2][3];
    char        names[4][16];
} Enemy;

/* --- type: Enemy instances --- */
#define Enemy_BaseGoblin_Index 0
#define Enemy_StrongerGoblin_Index 1

extern const Enemy Enemy_Instances[2];

const Enemy* Enemy_Find(unsigned int index);

#endif /* GDDL_GENERATED_68000_H */
