/* Auto-generated by the GDDL compiler (68000 / vbcc, C89). Do not edit by hand. */

#include "generated_68000_pools.h"

/* --- type: Enemy instances --- */
const Enemy Enemy_Instances[1] =
{
    { 1, { 0, 0 }, "x", { 0, 0 } },  /* Placeholder */
};

const Enemy* Enemy_Find(unsigned int index)
{
    return &Enemy_Instances[index];
}

/* --- pool: ActiveEnemies --- */
Enemy ActiveEnemies[8];
