#ifndef GDDL_GENERATED_68000_H
#define GDDL_GENERATED_68000_H

/* Auto-generated by the GDDL compiler (68000 / vbcc, C89). Do not edit by hand. */

/* --- type: Enemy (SoA field arrays) --- */
#define Enemy_Placeholder_Index 0

extern const signed long Enemy_hp[1];
extern const signed long Enemy_damage_min_max[1][2];
extern const char Enemy_name[1][16];
extern const signed long Enemy_position_x[1];
extern const signed long Enemy_position_y[1];

/* --- pool: ActiveEnemies (Enemy x 8, SoA reservation, uninitialized -- §22.4) --- */
extern signed long ActiveEnemies_hp[8];
extern signed long ActiveEnemies_damage_min_max[8][2];
extern char ActiveEnemies_name[8][16];
extern signed long ActiveEnemies_position_x[8];
extern signed long ActiveEnemies_position_y[8];

#endif /* GDDL_GENERATED_68000_H */
