; Auto-generated by the GDDL compiler (Z80 / SjASMPlus). Do not edit by hand.
; Scope: scalar (u8/u16), identifier-typed, and string N leaf fields, AoS only.
; --z80-pointer-table=on (§16.2)

; --- type: Enemy (AoS instance data) ---
Enemy_Sizeof equ 24
Enemy_Instances:
Enemy_Goblin:
	db 10	; damage_min_max[0]
	db 30	; damage_min_max[1]
	db 1	; grid[0]
	db 2	; grid[1]
	db 3	; grid[2]
	db 4	; grid[3]
	db 5	; grid[4]
	db 6	; grid[5]
	db "Al", 0, 0, 0, 0, 0, 0	; names[0]
	db "Bo", 0, 0, 0, 0, 0, 0	; names[1]

; --- type: Enemy registry (dense declaration-order index, no stable ID) ---
Enemy_Registry_Count equ 1
Enemy_Goblin_Index equ 0
Enemy_Registry:
	dw Enemy_Goblin

Enemy_Find:
	ld l, a
	ld h, 0
	add hl, hl
	ld de, Enemy_Registry
	add hl, de
	ld a, (hl)
	inc hl
	ld h, (hl)
	ld l, a
	ret
