; Auto-generated by the GDDL compiler (Z80 / z88dk-z80asm). Do not edit by hand.
; Scope: scalar (u8/u16) and identifier-typed leaf fields, layout=soa (string N not yet supported in SoA, matching 6502's own precedent).

; --- type: Enemy (SoA field arrays) ---

Enemy_hp:

Enemy_mp:

; --- pool: ActiveEnemies (Enemy x 4, SoA reservation, uninitialized -- §22.4) ---
ActiveEnemies_hp equ $a000
ActiveEnemies_mp equ $a004
