; Auto-generated by the GDDL compiler (Z80 / SjASMPlus). Do not edit by hand.
; Scope: scalar (u8/u16) and identifier-typed leaf fields, layout=soa (string N not yet supported in SoA, matching 6502's own precedent).

; --- domain: Rarity (indexed form, width u8) ---
Rarity_common equ 0
Rarity_rare equ 1

Rarity_JumpTable:
	dw Rarity_common_Handler
	dw Rarity_rare_Handler

Rarity_Dispatch:
	ld l, a
	ld h, 0
	add hl, hl
	ld de, Rarity_JumpTable
	add hl, de
	ld a, (hl)
	inc hl
	ld h, (hl)
	ld l, a
	jp (hl)

; --- type: Item (SoA field arrays) ---
Item_Sword_Index equ 0
Item_Bow_Index equ 1
Item_Shield_Index equ 2

Item_power:
	dw 42	; Sword
	dw 15	; Bow
	dw 8	; Shield

Item_rarity:
	db Rarity_rare	; Sword
	db Rarity_common	; Bow
	db Rarity_common	; Shield
