/* Auto-generated by the GDDL compiler (68000 / vbcc, C89). Do not edit by hand. */

#include "generated_68000_soa.h"

/* --- type: Creature (SoA field arrays) --- */
const unsigned char Creature_hp[2] = { 10, 8 };
const ActionAttack Creature_attack[2] = { ActionAttack_melee_weapon, ActionAttack_ranged_weapon };
const Rarity Creature_rarity[2] = { Rarity_common, Rarity_rare };

/* --- type: Item (SoA field arrays) --- */
const unsigned char Item_object_something1[2] = { 5, 2 };
const unsigned char Item_object_something2[2] = { 3, 9 };
const unsigned char Item_weight[2] = { 7, 4 };
const Element Item_element[2] = { Element_fire, Element_ice };
const char Item_name[2][16] = { "Sword", "Shield" };
