/* Auto-generated by the GDDL compiler (68000 / vbcc, C89). Do not edit by hand. */

#include "generated_68000_composition_u16.h"

/* --- type: Character instances --- */
const Character Character_Instances[1] =
{
    { { 60000, 12000 }, { 500 }, 42 },  /* Hero */
};

const Character* Character_Find(unsigned int index)
{
    return &Character_Instances[index];
}
