#ifndef GDDL_GENERATED_68000_H
#define GDDL_GENERATED_68000_H

/* Auto-generated by the GDDL compiler (68000 / vbcc, C89). Do not edit by hand. */

/* --- domain: ActionAttack (dense index, width u8) --- */
typedef unsigned char ActionAttack;
#define ActionAttack_melee_weapon ((ActionAttack)0)
#define ActionAttack_ranged_weapon ((ActionAttack)1)

/* --- domain: Element (dense index, width u16) --- */
typedef unsigned short Element;
#define Element_fire ((Element)0)
#define Element_ice ((Element)1)
#define Element_lightning ((Element)2)

/* --- domain: Rarity (dense index, width u32) --- */
typedef unsigned long Rarity;
#define Rarity_common ((Rarity)0)
#define Rarity_rare ((Rarity)1)

/* --- type: Creature --- */
typedef struct Creature
{
    unsigned char hp;
    ActionAttack attack;
    Rarity rarity;
} Creature;

/* --- type: Object --- */
typedef struct Object
{
    unsigned char something1;
    unsigned char something2;
} Object;

/* --- type: Item --- */
typedef struct Item
{
    Object object;
    unsigned char weight;
    Element element;
    char name[16];
} Item;

/* --- type: Creature instances --- */
#define Creature_Goblin_Index 0
#define Creature_Archer_Index 1

extern const Creature Creature_Instances[2];

const Creature* Creature_Find(unsigned int index);

/* --- type: Item instances --- */
#define Item_Sword_Index 0
#define Item_Shield_Index 1

extern const Item Item_Instances[2];

const Item* Item_Find(unsigned int index);

#endif /* GDDL_GENERATED_68000_H */
