; Auto-generated by the GDDL compiler (6502 / ACME). Do not edit by hand.
; Scope: scalar (u8/u16), identifier-typed, and string N leaf fields, AoS only.

; --- type: Item (AoS instance data) ---
Item_BasicSword:
	!byte 10	; power

; --- type: Item registry (dense declaration-order index, no stable ID) ---
Item_Registry_Count = 1
Item_BasicSword_Index = 0
Item_Registry_Lo:
	!byte <Item_BasicSword
Item_Registry_Hi:
	!byte >Item_BasicSword

Item_RegistryPtr = $02

Item_Find:
	LDA Item_Registry_Lo,X
	STA Item_RegistryPtr
	LDA Item_Registry_Hi,X
	STA Item_RegistryPtr+1
	RTS
