// Auto-generated by the GDDL compiler. Do not edit by hand.

#include "generated_cpp_split_OFF.h"

namespace GDDL
{

namespace Item_Instances
{
    const Item BasicSword = { 10 };
} // namespace Item_Instances

namespace Item_Registry
{
    const std::array<Entry, 1> Table =
    {
        Entry{ 0x50632af66a000c59ULL, "BasicSword", &Item_Instances::BasicSword },
    };

    const Item* Find(uint64_t instance_id)
    {
        std::size_t lo = 0, hi = Table.size();

        while (lo < hi)
        {
            std::size_t mid = lo + (hi - lo) / 2;

            if (Table[mid].instance_id < instance_id)
            {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if (lo < Table.size() && Table[lo].instance_id == instance_id)
        {
            return Table[lo].data;
        }

        return nullptr;
    }

    const Item* Find(std::string_view name)
    {
        for (const auto& entry : Table)
        {
            if (entry.name == name)
            {
                return entry.data;
            }
        }

        return nullptr;
    }
} // namespace Item_Registry
} // namespace GDDL
