// Auto-generated by the GDDL compiler (6502 / KickAssembler). Do not edit by hand.
.encoding "ascii"
// Scope: scalar (u8/u16), identifier-typed, and string N leaf fields, AoS only.

// --- domain: Rarity (indexed form, width u8) ---
.label Rarity_common = 0
.label Rarity_rare = 1
.label Rarity_epic = 2

Rarity_JumpTable_Lo:
	.byte <Rarity_common_Handler
	.byte <Rarity_rare_Handler
	.byte <Rarity_epic_Handler
Rarity_JumpTable_Hi:
	.byte >Rarity_common_Handler
	.byte >Rarity_rare_Handler
	.byte >Rarity_epic_Handler

.label Rarity_DispatchPtr = $04

Rarity_Dispatch:
	lda Rarity_JumpTable_Lo,x
	sta Rarity_DispatchPtr
	lda Rarity_JumpTable_Hi,x
	sta Rarity_DispatchPtr+1
	jmp (Rarity_DispatchPtr)

// --- type: Item (AoS instance data) ---
Item_BasicSword:
	.byte 10	// power

// --- type: Item registry (dense declaration-order index, no stable ID) ---
.label Item_Registry_Count = 1
.label Item_BasicSword_Index = 0
Item_Registry_Lo:
	.byte <Item_BasicSword
Item_Registry_Hi:
	.byte >Item_BasicSword

.label Item_RegistryPtr = $02

Item_Find:
	lda Item_Registry_Lo,x
	sta Item_RegistryPtr
	lda Item_Registry_Hi,x
	sta Item_RegistryPtr+1
	rts
