#ifndef GDDL_GENERATED_H
#define GDDL_GENERATED_H

// Auto-generated by the GDDL compiler. Do not edit by hand.

#include <cstdint>
#include <array>
#include <string_view>

namespace GDDL
{

enum class ActionAttack : uint64_t
{
    melee_weapon = 0x5c96a731d7d47e03ULL,
    ranged_weapon = 0xaa92e2b5323e5154ULL,
};

struct Object
{
    uint32_t something1;
    uint32_t something2;
};

namespace Object_Instances
{
    inline constexpr Object DefaultObject = { 0, 0 };
    inline constexpr Object HeavyObject = { 100, 50 };
    inline constexpr Object LightObject = { 5, 50 };
}

namespace Object_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        const Object* data;
    };

    inline constexpr std::array<Entry, 3> Table =
    {
        Entry{ 0x4e4417bdfce7a91aULL, "HeavyObject", &Object_Instances::HeavyObject },
        Entry{ 0xad84053e592e7248ULL, "DefaultObject", &Object_Instances::DefaultObject },
        Entry{ 0xea3fb911673e5dc9ULL, "LightObject", &Object_Instances::LightObject },
    };

    constexpr const Object* Find(uint64_t instance_id)
    {
        std::size_t lo = 0, hi = Table.size();

        while (lo < hi)
        {
            std::size_t mid = lo + (hi - lo) / 2;

            if (Table[mid].instance_id < instance_id)
            {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if (lo < Table.size() && Table[lo].instance_id == instance_id)
        {
            return Table[lo].data;
        }

        return nullptr;
    }

    constexpr const Object* Find(std::string_view name)
    {
        for (const auto& entry : Table)
        {
            if (entry.name == name)
            {
                return entry.data;
            }
        }

        return nullptr;
    }
} // namespace Object_Registry
} // namespace GDDL

#endif // GDDL_GENERATED_H
