#ifndef GDDL_GENERATED_H
#define GDDL_GENERATED_H

// Auto-generated by the GDDL compiler. Do not edit by hand.

#include <cstdint>
#include <array>
#include <string_view>

namespace GDDL
{

struct Stats
{
    uint16_t hp;
    uint16_t mp;
};

struct Equipment
{
    uint16_t weapon_power;
};

struct Character
{
    Stats stats;
    Equipment equipment;
    uint16_t level;
};

namespace Stats_Instances
{
}

namespace Stats_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        const Stats* data;
    };

    extern const std::array<Entry, 0> Table;

    const Stats* Find(uint64_t instance_id);

    const Stats* Find(std::string_view name);
} // namespace Stats_Registry

namespace Equipment_Instances
{
}

namespace Equipment_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        const Equipment* data;
    };

    extern const std::array<Entry, 0> Table;

    const Equipment* Find(uint64_t instance_id);

    const Equipment* Find(std::string_view name);
} // namespace Equipment_Registry

namespace Character_Instances
{
    extern const Character Hero;
}

namespace Character_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        const Character* data;
    };

    extern const std::array<Entry, 1> Table;

    const Character* Find(uint64_t instance_id);

    const Character* Find(std::string_view name);
} // namespace Character_Registry
} // namespace GDDL

#endif // GDDL_GENERATED_H
