// Auto-generated by the GDDL compiler. Do not edit by hand.

#include "generated_composition_nested_u16_fields.h"

namespace GDDL
{

namespace Stats_Instances
{
} // namespace Stats_Instances

namespace Stats_Registry
{
    const std::array<Entry, 0> Table = {};

    const Stats* Find(uint64_t instance_id)
    {
        std::size_t lo = 0, hi = Table.size();

        while (lo < hi)
        {
            std::size_t mid = lo + (hi - lo) / 2;

            if (Table[mid].instance_id < instance_id)
            {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if (lo < Table.size() && Table[lo].instance_id == instance_id)
        {
            return Table[lo].data;
        }

        return nullptr;
    }

    const Stats* Find(std::string_view name)
    {
        for (const auto& entry : Table)
        {
            if (entry.name == name)
            {
                return entry.data;
            }
        }

        return nullptr;
    }
} // namespace Stats_Registry

namespace Equipment_Instances
{
} // namespace Equipment_Instances

namespace Equipment_Registry
{
    const std::array<Entry, 0> Table = {};

    const Equipment* Find(uint64_t instance_id)
    {
        std::size_t lo = 0, hi = Table.size();

        while (lo < hi)
        {
            std::size_t mid = lo + (hi - lo) / 2;

            if (Table[mid].instance_id < instance_id)
            {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if (lo < Table.size() && Table[lo].instance_id == instance_id)
        {
            return Table[lo].data;
        }

        return nullptr;
    }

    const Equipment* Find(std::string_view name)
    {
        for (const auto& entry : Table)
        {
            if (entry.name == name)
            {
                return entry.data;
            }
        }

        return nullptr;
    }
} // namespace Equipment_Registry

namespace Character_Instances
{
    const Character Hero = { Stats{ 60000, 12000 }, Equipment{ 500 }, 42 };
} // namespace Character_Instances

namespace Character_Registry
{
    const std::array<Entry, 1> Table =
    {
        Entry{ 0x5ff2940d2286ca5cULL, "Hero", &Character_Instances::Hero },
    };

    const Character* Find(uint64_t instance_id)
    {
        std::size_t lo = 0, hi = Table.size();

        while (lo < hi)
        {
            std::size_t mid = lo + (hi - lo) / 2;

            if (Table[mid].instance_id < instance_id)
            {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if (lo < Table.size() && Table[lo].instance_id == instance_id)
        {
            return Table[lo].data;
        }

        return nullptr;
    }

    const Character* Find(std::string_view name)
    {
        for (const auto& entry : Table)
        {
            if (entry.name == name)
            {
                return entry.data;
            }
        }

        return nullptr;
    }
} // namespace Character_Registry
} // namespace GDDL
