#ifndef GDDL_GENERATED_H
#define GDDL_GENERATED_H

// Auto-generated by the GDDL compiler. Do not edit by hand.

#include <cstdint>
#include <array>
#include <string_view>

namespace GDDL
{

struct Stats
{
    uint32_t value;
};

namespace Stats_Instances
{
    inline constexpr Stats OnlyOne = { 42 };
}

namespace Stats_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        const Stats* data;
    };

    inline constexpr std::array<Entry, 1> Table =
    {
        Entry{ 0x5e71436bc9c63862ULL, "OnlyOne", &Stats_Instances::OnlyOne },
    };

    constexpr const Stats* Find(uint64_t instance_id)
    {
        std::size_t lo = 0, hi = Table.size();

        while (lo < hi)
        {
            std::size_t mid = lo + (hi - lo) / 2;

            if (Table[mid].instance_id < instance_id)
            {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if (lo < Table.size() && Table[lo].instance_id == instance_id)
        {
            return Table[lo].data;
        }

        return nullptr;
    }

    constexpr const Stats* Find(std::string_view name)
    {
        for (const auto& entry : Table)
        {
            if (entry.name == name)
            {
                return entry.data;
            }
        }

        return nullptr;
    }
} // namespace Stats_Registry
} // namespace GDDL

#endif // GDDL_GENERATED_H
