; Auto-generated by the GDDL compiler (Z80 / SjASMPlus). Do not edit by hand.
; Scope: scalar (u8/u16), identifier-typed, and string N leaf fields, AoS only.
; --z80-pointer-table=on (§16.2)

; --- domain: Element (indexed form, width u8) ---
Element_fire equ 0
Element_ice equ 1
Element_lightning equ 2

Element_JumpTable:
	dw Element_fire_Handler
	dw Element_ice_Handler
	dw Element_lightning_Handler

Element_Dispatch:
	ld l, a
	ld h, 0
	add hl, hl
	ld de, Element_JumpTable
	add hl, de
	ld a, (hl)
	inc hl
	ld h, (hl)
	ld l, a
	jp (hl)

; --- type: Weapon (AoS instance data) ---
Weapon_Sizeof equ 2
Weapon_Instances:
Weapon_Sword:
	db 10	; damage
	db Element_fire	; element
Weapon_Bow:
	db 5	; damage
	db Element_lightning	; element

; --- type: Weapon registry (dense declaration-order index, no stable ID) ---
Weapon_Registry_Count equ 2
Weapon_Sword_Index equ 0
Weapon_Bow_Index equ 1
Weapon_Registry:
	dw Weapon_Sword
	dw Weapon_Bow

Weapon_Find:
	ld l, a
	ld h, 0
	add hl, hl
	ld de, Weapon_Registry
	add hl, de
	ld a, (hl)
	inc hl
	ld h, (hl)
	ld l, a
	ret
