; Auto-generated by the GDDL compiler (6502 / ACME). Do not edit by hand.
; Scope: scalar (u8/u16), identifier-typed, and string N leaf fields, AoS only.

; --- type: Character (AoS instance data) ---
Character_Hero:
	!word 60000	; stats_hp
	!word 12000	; stats_mp
	!word 500	; equipment_weapon_power
	!word 42	; level

; --- type: Character registry (dense declaration-order index, no stable ID) ---
Character_Registry_Count = 1
Character_Hero_Index = 0
Character_Registry_Lo:
	!byte <Character_Hero
Character_Registry_Hi:
	!byte >Character_Hero

Character_RegistryPtr = $02

Character_Find:
	LDA Character_Registry_Lo,X
	STA Character_RegistryPtr
	LDA Character_Registry_Hi,X
	STA Character_RegistryPtr+1
	RTS
