// Auto-generated by the GDDL compiler (6502 / KickAssembler). Do not edit by hand.
.encoding "ascii"
// Scope: scalar (u8/u16) and identifier-typed leaf fields, layout=soa (string N not yet supported in SoA).

// --- type: Enemy (SoA field arrays) ---
Enemy_hp:
Enemy_mp_Lo:
Enemy_mp_Hi:

// --- pool: ActiveEnemies (Enemy x 4, SoA reservation, uninitialized -- §22.4) ---
.label ActiveEnemies_hp = $a000
.label ActiveEnemies_mp_Lo = $a004
.label ActiveEnemies_mp_Hi = $a008
