// Auto-generated by the GDDL compiler (6502 / KickAssembler). Do not edit by hand.
.encoding "ascii"
// Scope: scalar (u8/u16), identifier-typed, and string N leaf fields, AoS only.

// --- type: Enemy (AoS instance data) ---
Enemy_Goblin:
	.byte 10	// damage_min_max[0]
	.byte 30	// damage_min_max[1]
	.byte 1	// grid[0]
	.byte 2	// grid[1]
	.byte 3	// grid[2]
	.byte 4	// grid[3]
	.byte 5	// grid[4]
	.byte 6	// grid[5]
	.text "Al"	// names[0]
	.byte 0, 0, 0, 0, 0, 0
	.text "Bo"	// names[1]
	.byte 0, 0, 0, 0, 0, 0

// --- type: Enemy registry (dense declaration-order index, no stable ID) ---
.label Enemy_Registry_Count = 1
.label Enemy_Goblin_Index = 0
Enemy_Registry_Lo:
	.byte <Enemy_Goblin
Enemy_Registry_Hi:
	.byte >Enemy_Goblin

.label Enemy_RegistryPtr = $02

Enemy_Find:
	lda Enemy_Registry_Lo,x
	sta Enemy_RegistryPtr
	lda Enemy_Registry_Hi,x
	sta Enemy_RegistryPtr+1
	rts
