; Auto-generated by the GDDL compiler (6502 / ACME). Do not edit by hand.
; Scope: scalar (u8/u16), identifier-typed, and string N leaf fields, AoS only.

; --- type: Enemy (AoS instance data) ---
Enemy_Goblin:
	!byte 10	; damage_min_max[0]
	!byte 30	; damage_min_max[1]
	!byte 1	; grid[0]
	!byte 2	; grid[1]
	!byte 3	; grid[2]
	!byte 4	; grid[3]
	!byte 5	; grid[4]
	!byte 6	; grid[5]
	!text "Al"	; names[0]
	!byte 0, 0, 0, 0, 0, 0
	!text "Bo"	; names[1]
	!byte 0, 0, 0, 0, 0, 0

; --- type: Enemy registry (dense declaration-order index, no stable ID) ---
Enemy_Registry_Count = 1
Enemy_Goblin_Index = 0
Enemy_Registry_Lo:
	!byte <Enemy_Goblin
Enemy_Registry_Hi:
	!byte >Enemy_Goblin

Enemy_RegistryPtr = $02

Enemy_Find:
	LDA Enemy_Registry_Lo,X
	STA Enemy_RegistryPtr
	LDA Enemy_Registry_Hi,X
	STA Enemy_RegistryPtr+1
	RTS
