// Auto-generated by the GDDL compiler (6502 / KickAssembler). Do not edit by hand.
.encoding "ascii"
// Scope: scalar (u8/u16), identifier-typed, and string N leaf fields, AoS only.

// --- type: Character (AoS instance data) ---
Character_Hero:
	.word 60000	// stats_hp
	.word 12000	// stats_mp
	.word 500	// equipment_weapon_power
	.word 42	// level

// --- type: Character registry (dense declaration-order index, no stable ID) ---
.label Character_Registry_Count = 1
.label Character_Hero_Index = 0
Character_Registry_Lo:
	.byte <Character_Hero
Character_Registry_Hi:
	.byte >Character_Hero

.label Character_RegistryPtr = $02

Character_Find:
	lda Character_Registry_Lo,x
	sta Character_RegistryPtr
	lda Character_Registry_Hi,x
	sta Character_RegistryPtr+1
	rts
