/* Auto-generated by the GDDL compiler (Z80 / z88dk C mode). Do not edit by hand. */
/* Definitions -- C89, targeting zsdcc. Compile with: zcc +<target> -compiler=sdcc ... */
/* --z80-pointer-table=on (SPEC S16.2) */

#include "gddl_z80_export.h"

/* --- type: Character instance data (AoS) --- */
const Character Character_Instances[Character_Registry_Count] = {
    { 60000, 12000, 500, 42 },   /* [0] Hero */
};

const Character *const Character_Registry[Character_Registry_Count] = {
    &Character_Instances[Character_Hero_Index],   /* Hero */
};

const Character *Character_Find(unsigned char index)
{
    return Character_Registry[index];
}

