/* Auto-generated by the GDDL compiler (Z80 / z88dk C mode). Do not edit by hand. */
/* Definitions -- C89, targeting zsdcc. Compile with: zcc +<target> -compiler=sdcc ... */
/* --z80-pointer-table=on (SPEC S16.2) */

#include "gddl_z80_export.h"

/* --- type: Creature instance data (AoS) --- */
const Creature Creature_Instances[Creature_Registry_Count] = {
    { 10, ActionAttack_melee_weapon },   /* [0] Goblin */
    { 8, ActionAttack_ranged_weapon },   /* [1] Archer */
};

const Creature *const Creature_Registry[Creature_Registry_Count] = {
    &Creature_Instances[Creature_Goblin_Index],   /* Goblin */
    &Creature_Instances[Creature_Archer_Index],   /* Archer */
};

const Creature *Creature_Find(unsigned char index)
{
    return Creature_Registry[index];
}

