/* Auto-generated by the GDDL compiler (Z80 / z88dk C mode). Do not edit by hand. */
/* Header: declarations only -- C89, targeting zsdcc. Compile with: zcc +<target> -compiler=sdcc ... */
/* --z80-pointer-table=on (SPEC S16.2) */

#ifndef GDDL_Z80_EXPORT_H
#define GDDL_Z80_EXPORT_H

/* --- domain: ActionAttack (indexed form, width u8) --- */
#define ActionAttack_melee_weapon 0
#define ActionAttack_ranged_weapon 1
#define ActionAttack_Count 2

/* --- type: Creature (AoS, sizeof == 2) --- */
typedef struct {
    unsigned char hp;
    unsigned char attack;
} Creature;

#define Creature_Registry_Count 2
#define Creature_Goblin_Index 0
#define Creature_Archer_Index 1

extern const Creature Creature_Instances[Creature_Registry_Count];
extern const Creature *const Creature_Registry[Creature_Registry_Count];
const Creature *Creature_Find(unsigned char index);

#endif /* GDDL_Z80_EXPORT_H */
