#ifndef GDDL_GENERATED_H
#define GDDL_GENERATED_H

// Auto-generated by the GDDL compiler. Do not edit by hand.

#include <cstdint>
#include <array>
#include <string_view>

namespace GDDL
{

namespace Vec2_SoA
{
    inline constexpr std::array<int32_t, 0> x = {};

    inline constexpr std::array<int32_t, 0> y = {};
}

namespace Vec2_SoA_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        std::size_t row;
    };

    inline constexpr std::array<Entry, 0> Table = {};

    constexpr std::size_t Find(uint64_t instance_id)
    {
        std::size_t lo = 0, hi = Table.size();

        while (lo < hi)
        {
            std::size_t mid = lo + (hi - lo) / 2;

            if (Table[mid].instance_id < instance_id)
            {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if (lo < Table.size() && Table[lo].instance_id == instance_id)
        {
            return Table[lo].row;
        }

        return static_cast<std::size_t>(-1);
    }

    constexpr std::size_t Find(std::string_view name)
    {
        for (const auto& entry : Table)
        {
            if (entry.name == name)
            {
                return entry.row;
            }
        }

        return static_cast<std::size_t>(-1);
    }
} // namespace Vec2_SoA_Registry

namespace Enemy_SoA
{
    inline constexpr std::array<int32_t, 0> hp = {};

    inline constexpr std::array<std::array<int32_t, 2>, 0> damage_min_max = {};

    inline constexpr std::array<char, 0> name = {};

    inline constexpr std::array<int32_t, 0> position_x = {};

    inline constexpr std::array<int32_t, 0> position_y = {};
}

namespace Enemy_SoA_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        std::size_t row;
    };

    inline constexpr std::array<Entry, 0> Table = {};

    constexpr std::size_t Find(uint64_t instance_id)
    {
        std::size_t lo = 0, hi = Table.size();

        while (lo < hi)
        {
            std::size_t mid = lo + (hi - lo) / 2;

            if (Table[mid].instance_id < instance_id)
            {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if (lo < Table.size() && Table[lo].instance_id == instance_id)
        {
            return Table[lo].row;
        }

        return static_cast<std::size_t>(-1);
    }

    constexpr std::size_t Find(std::string_view name)
    {
        for (const auto& entry : Table)
        {
            if (entry.name == name)
            {
                return entry.row;
            }
        }

        return static_cast<std::size_t>(-1);
    }
} // namespace Enemy_SoA_Registry

// §17.5: compile-time schema table, for comparison against
// whatever a loaded .gddldata.bin/.gddlmeta.json pair claims at
// runtime (§17.6). schema_hash/record_size here are computed by
// the EXACT SAME functions the .gddldata.bin exporter calls --
// see export_cpp.py's compute_schema_hash/compute_record_size,
// shared with export_binary.py, never a second implementation.
struct SchemaEntry
{
    std::string_view type_name;
    uint64_t schema_hash;
    uint32_t record_size;
};

inline constexpr std::array<SchemaEntry, 2> SchemaTable =
{
    SchemaEntry{ "Vec2", 0x4bfd1adc78ac8f7aULL, 8 },
    SchemaEntry{ "Enemy", 0x0e781b414cf70b7fULL, 36 },
};

namespace ActiveEnemies_SoA
{
    inline int32_t hp[8];
    inline std::array<int32_t, 2> damage_min_max[8];
    inline char name[128];
    inline int32_t position_x[8];
    inline int32_t position_y[8];
}

} // namespace GDDL

#endif // GDDL_GENERATED_H
