#ifndef GDDL_GENERATED_H
#define GDDL_GENERATED_H

// Auto-generated by the GDDL compiler. Do not edit by hand.

#include <cstdint>
#include <array>
#include <string_view>

namespace GDDL
{

struct Vec2
{
    int32_t x;
    int32_t y;
};

struct Enemy
{
    int32_t                hp;
    std::array<int32_t, 2> damage_min_max;
    char                   name[16];
    Vec2                   position;
};

namespace Vec2_Instances
{
}

namespace Vec2_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        const Vec2* data;
    };

    inline constexpr std::array<Entry, 0> Table = {};

    constexpr const Vec2* Find(uint64_t instance_id)
    {
        std::size_t lo = 0, hi = Table.size();

        while (lo < hi)
        {
            std::size_t mid = lo + (hi - lo) / 2;

            if (Table[mid].instance_id < instance_id)
            {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if (lo < Table.size() && Table[lo].instance_id == instance_id)
        {
            return Table[lo].data;
        }

        return nullptr;
    }

    constexpr const Vec2* Find(std::string_view name)
    {
        for (const auto& entry : Table)
        {
            if (entry.name == name)
            {
                return entry.data;
            }
        }

        return nullptr;
    }
} // namespace Vec2_Registry

namespace Enemy_Instances
{
}

namespace Enemy_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        const Enemy* data;
    };

    inline constexpr std::array<Entry, 0> Table = {};

    constexpr const Enemy* Find(uint64_t instance_id)
    {
        std::size_t lo = 0, hi = Table.size();

        while (lo < hi)
        {
            std::size_t mid = lo + (hi - lo) / 2;

            if (Table[mid].instance_id < instance_id)
            {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if (lo < Table.size() && Table[lo].instance_id == instance_id)
        {
            return Table[lo].data;
        }

        return nullptr;
    }

    constexpr const Enemy* Find(std::string_view name)
    {
        for (const auto& entry : Table)
        {
            if (entry.name == name)
            {
                return entry.data;
            }
        }

        return nullptr;
    }
} // namespace Enemy_Registry

// §17.5: compile-time schema table, for comparison against
// whatever a loaded .gddldata.bin/.gddlmeta.json pair claims at
// runtime (§17.6). schema_hash/record_size here are computed by
// the EXACT SAME functions the .gddldata.bin exporter calls --
// see export_cpp.py's compute_schema_hash/compute_record_size,
// shared with export_binary.py, never a second implementation.
struct SchemaEntry
{
    std::string_view type_name;
    uint64_t schema_hash;
    uint32_t record_size;
};

inline constexpr std::array<SchemaEntry, 2> SchemaTable =
{
    SchemaEntry{ "Vec2", 0x4bfd1adc78ac8f7aULL, 8 },
    SchemaEntry{ "Enemy", 0x0e781b414cf70b7fULL, 36 },
};

inline Enemy ActiveEnemies[8];

} // namespace GDDL

#endif // GDDL_GENERATED_H
