#ifndef GDDL_GENERATED_H
#define GDDL_GENERATED_H

// Auto-generated by the GDDL compiler. Do not edit by hand.

#include <cstdint>
#include <array>
#include <string_view>

namespace GDDL
{

enum class ActionAttack : uint64_t
{
    melee_weapon  = 0x5c96a731d7d47e03ULL, // Standard attack done with a melee weapon
    ranged_weapon = 0xaa92e2b5323e5154ULL, // Standard attack done with a ranged weapon
};

enum class ActionAttack_Indexed : uint8_t
{
    melee_weapon  = 0, // Standard attack done with a melee weapon
    ranged_weapon = 1, // Standard attack done with a ranged weapon
};

enum class Element : uint64_t
{
    fire      = 0x9bcf40f6874d9103ULL, // Elemental fire damage type
    ice       = 0x8304148e0f4f19acULL, // Elemental ice damage type
    lightning = 0x2ac1c587b5474f2dULL, // Elemental lightning damage type
    poison    = 0xfa09e3b805721ebfULL, // Elemental poison damage type
};

namespace Object_SoA
{
    inline constexpr std::array<uint32_t, 6> something1 = { 0, 100, 5, 10, 1, 10 };

    inline constexpr std::array<uint32_t, 6> something2 = { 0, 50, 50, 20, 2, 2 };
}

namespace Object_SoA_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        std::size_t row;
    };

    inline constexpr std::array<Entry, 6> Table =
    {
        Entry{ 0x4e4417bdfce7a91aULL, "HeavyObject", 1 },
        Entry{ 0xad84053e592e7248ULL, "DefaultObject", 0 },
        Entry{ 0xea3fb911673e5dc9ULL, "LightObject", 2 },
        Entry{ 0xed9105d6ab5f2814ULL, "RealObjectGen1", 4 },
        Entry{ 0xed9108d6ab5f2d2dULL, "RealObjectGen2", 5 },
        Entry{ 0xf334fa27c5ce1648ULL, "BaseObject", 3 },
    };

    constexpr std::size_t Find(uint64_t instance_id)
    {
        std::size_t lo = 0, hi = Table.size();

        while (lo < hi)
        {
            std::size_t mid = lo + (hi - lo) / 2;

            if (Table[mid].instance_id < instance_id)
            {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if (lo < Table.size() && Table[lo].instance_id == instance_id)
        {
            return Table[lo].row;
        }

        return static_cast<std::size_t>(-1);
    }

    constexpr std::size_t Find(std::string_view name)
    {
        for (const auto& entry : Table)
        {
            if (entry.name == name)
            {
                return entry.row;
            }
        }

        return static_cast<std::size_t>(-1);
    }
} // namespace Object_SoA_Registry

namespace Item_SoA
{
    inline constexpr std::array<uint32_t, 3> object_something1 = { 10, 99, 10 };

    inline constexpr std::array<uint32_t, 3> object_something2 = { 20, 100, 20 };

    inline constexpr std::array<uint32_t, 3> weight = { 5, 7, 50 };

    inline constexpr std::array<Element, 3> element = { Element::fire, Element::ice, Element::lightning };

    inline constexpr std::array<char, 48> name =
    {
        'S', 'w', 'o', 'r', 'd', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', '\0', 'S', 'h', 'i', 'e', 'l', 'd', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0'
    };

    inline constexpr std::array<ActionAttack_Indexed, 3> fast_dispatch = { ActionAttack_Indexed::melee_weapon, ActionAttack_Indexed::ranged_weapon, ActionAttack_Indexed::melee_weapon };
}

namespace Item_SoA_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        std::size_t row;
    };

    inline constexpr std::array<Entry, 3> Table =
    {
        Entry{ 0x8ad19844df88b655ULL, "ItemViaBareModify", 1 },
        Entry{ 0xb1ea277c9f6610e8ULL, "ItemCopy", 2 },
        Entry{ 0xf1112704e607b426ULL, "ItemViaFullReplace", 0 },
    };

    constexpr std::size_t Find(uint64_t instance_id)
    {
        std::size_t lo = 0, hi = Table.size();

        while (lo < hi)
        {
            std::size_t mid = lo + (hi - lo) / 2;

            if (Table[mid].instance_id < instance_id)
            {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if (lo < Table.size() && Table[lo].instance_id == instance_id)
        {
            return Table[lo].row;
        }

        return static_cast<std::size_t>(-1);
    }

    constexpr std::size_t Find(std::string_view name)
    {
        for (const auto& entry : Table)
        {
            if (entry.name == name)
            {
                return entry.row;
            }
        }

        return static_cast<std::size_t>(-1);
    }
} // namespace Item_SoA_Registry

// §17.5: compile-time schema table, for comparison against
// whatever a loaded .gddldata.bin/.gddlmeta.json pair claims at
// runtime (§17.6). schema_hash/record_size here are computed by
// the EXACT SAME functions the .gddldata.bin exporter calls --
// see export_cpp.py's compute_schema_hash/compute_record_size,
// shared with export_binary.py, never a second implementation.
struct SchemaEntry
{
    std::string_view type_name;
    uint64_t schema_hash;
    uint32_t record_size;
};

inline constexpr std::array<SchemaEntry, 2> SchemaTable =
{
    SchemaEntry{ "Object", 0xc3b65b8d9dc943b8ULL, 8 },
    SchemaEntry{ "Item", 0x2c99385395d2d57eULL, 37 },
};

} // namespace GDDL

#endif // GDDL_GENERATED_H
