#ifndef GDDL_GENERATED_H
#define GDDL_GENERATED_H

// Auto-generated by the GDDL compiler. Do not edit by hand.

#include <cstdint>
#include <array>
#include <string_view>

namespace GDDL
{

namespace ComponentFlags
{
    constexpr uint64_t none              = 0;
    constexpr uint64_t is_damageable     = 1ULL << 0;
    constexpr uint64_t is_pickupable     = 1ULL << 1;
    constexpr uint64_t is_equippable     = 1ULL << 3;
    constexpr uint64_t is_movable        = 1ULL << 2;
    constexpr uint64_t is_controllable   = 1ULL << 4;
    constexpr uint64_t is_passive_effect = 1ULL << 5;
    constexpr uint64_t is_use            = 1ULL << 6;
    constexpr uint64_t is_attack         = 1ULL << 7;
}

struct Entity
{
    uint64_t component_flags;
};

namespace Entity_Instances
{
    inline constexpr Entity Player = { 20ULL };
    inline constexpr Entity PlayerDisarmed = { 4ULL };
}

namespace Entity_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        const Entity* data;
    };

    inline constexpr std::array<Entry, 2> Table =
    {
        Entry{ 0x4c0f57f422364dc0ULL, "PlayerDisarmed", &Entity_Instances::PlayerDisarmed },
        Entry{ 0xc5ce7b9da43a1177ULL, "Player", &Entity_Instances::Player },
    };

    constexpr const Entity* Find(uint64_t instance_id)
    {
        std::size_t lo = 0, hi = Table.size();

        while (lo < hi)
        {
            std::size_t mid = lo + (hi - lo) / 2;

            if (Table[mid].instance_id < instance_id)
            {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if (lo < Table.size() && Table[lo].instance_id == instance_id)
        {
            return Table[lo].data;
        }

        return nullptr;
    }

    constexpr const Entity* Find(std::string_view name)
    {
        for (const auto& entry : Table)
        {
            if (entry.name == name)
            {
                return entry.data;
            }
        }

        return nullptr;
    }
} // namespace Entity_Registry

// §17.5: compile-time schema table, for comparison against
// whatever a loaded .gddldata.bin/.gddlmeta.json pair claims at
// runtime (§17.6). schema_hash/record_size here are computed by
// the EXACT SAME functions the .gddldata.bin exporter calls --
// see export_cpp.py's compute_schema_hash/compute_record_size,
// shared with export_binary.py, never a second implementation.
struct SchemaEntry
{
    std::string_view type_name;
    uint64_t schema_hash;
    uint32_t record_size;
};

inline constexpr std::array<SchemaEntry, 1> SchemaTable =
{
    SchemaEntry{ "Entity", 0x001d4b684c365f7fULL, 8 },
};

} // namespace GDDL

#endif // GDDL_GENERATED_H
