#ifndef GDDL_GENERATED_H
#define GDDL_GENERATED_H

// Auto-generated by the GDDL compiler. Do not edit by hand.

#include <cstdint>
#include <array>
#include <string_view>

namespace GDDL
{

struct Object
{
    uint32_t something1;
    uint32_t something2;
};

namespace Object_Instances
{
}

namespace Object_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        const Object* data;
    };

    inline constexpr std::array<Entry, 0> Table = {};

    constexpr const Object* Find(uint64_t instance_id)
    {
        std::size_t lo = 0, hi = Table.size();

        while (lo < hi)
        {
            std::size_t mid = lo + (hi - lo) / 2;

            if (Table[mid].instance_id < instance_id)
            {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if (lo < Table.size() && Table[lo].instance_id == instance_id)
        {
            return Table[lo].data;
        }

        return nullptr;
    }

    constexpr const Object* Find(std::string_view name)
    {
        for (const auto& entry : Table)
        {
            if (entry.name == name)
            {
                return entry.data;
            }
        }

        return nullptr;
    }
} // namespace Object_Registry
} // namespace GDDL

#endif // GDDL_GENERATED_H
