#ifndef GDDL_GENERATED_H
#define GDDL_GENERATED_H

// Auto-generated by the GDDL compiler. Do not edit by hand.

#include <cstdint>
#include <array>
#include <string_view>

namespace GDDL
{

struct Stats
{
    uint32_t value;
};

namespace Stats_Instances
{
    inline constexpr Stats Entry00 = { 0 };
    inline constexpr Stats Entry01 = { 1 };
    inline constexpr Stats Entry02 = { 2 };
    inline constexpr Stats Entry03 = { 3 };
    inline constexpr Stats Entry04 = { 4 };
    inline constexpr Stats Entry05 = { 5 };
    inline constexpr Stats Entry06 = { 6 };
    inline constexpr Stats Entry07 = { 7 };
    inline constexpr Stats Entry08 = { 8 };
    inline constexpr Stats Entry09 = { 9 };
    inline constexpr Stats Entry10 = { 10 };
    inline constexpr Stats Entry11 = { 11 };
    inline constexpr Stats Entry12 = { 12 };
    inline constexpr Stats Entry13 = { 13 };
    inline constexpr Stats Entry14 = { 14 };
    inline constexpr Stats Entry15 = { 15 };
    inline constexpr Stats Entry16 = { 16 };
    inline constexpr Stats Entry17 = { 17 };
    inline constexpr Stats Entry18 = { 18 };
    inline constexpr Stats Entry19 = { 19 };
}

namespace Stats_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        const Stats* data;
    };

    inline constexpr std::array<Entry, 20> Table =
    {
        Entry{ 0xaa04cd91d9a757e0ULL, "Entry04", &Stats_Instances::Entry04 },
        Entry{ 0xaa04ce91d9a75993ULL, "Entry05", &Stats_Instances::Entry05 },
        Entry{ 0xaa04cf91d9a75b46ULL, "Entry06", &Stats_Instances::Entry06 },
        Entry{ 0xaa04d091d9a75cf9ULL, "Entry07", &Stats_Instances::Entry07 },
        Entry{ 0xaa04d191d9a75eacULL, "Entry00", &Stats_Instances::Entry00 },
        Entry{ 0xaa04d291d9a7605fULL, "Entry01", &Stats_Instances::Entry01 },
        Entry{ 0xaa04d391d9a76212ULL, "Entry02", &Stats_Instances::Entry02 },
        Entry{ 0xaa04d491d9a763c5ULL, "Entry03", &Stats_Instances::Entry03 },
        Entry{ 0xaa04d991d9a76c44ULL, "Entry08", &Stats_Instances::Entry08 },
        Entry{ 0xaa04da91d9a76df7ULL, "Entry09", &Stats_Instances::Entry09 },
        Entry{ 0xaa085091d9aa6c50ULL, "Entry17", &Stats_Instances::Entry17 },
        Entry{ 0xaa085191d9aa6e03ULL, "Entry16", &Stats_Instances::Entry16 },
        Entry{ 0xaa085291d9aa6fb6ULL, "Entry15", &Stats_Instances::Entry15 },
        Entry{ 0xaa085391d9aa7169ULL, "Entry14", &Stats_Instances::Entry14 },
        Entry{ 0xaa085491d9aa731cULL, "Entry13", &Stats_Instances::Entry13 },
        Entry{ 0xaa085591d9aa74cfULL, "Entry12", &Stats_Instances::Entry12 },
        Entry{ 0xaa085691d9aa7682ULL, "Entry11", &Stats_Instances::Entry11 },
        Entry{ 0xaa085791d9aa7835ULL, "Entry10", &Stats_Instances::Entry10 },
        Entry{ 0xaa085e91d9aa841aULL, "Entry19", &Stats_Instances::Entry19 },
        Entry{ 0xaa085f91d9aa85cdULL, "Entry18", &Stats_Instances::Entry18 },
    };

    constexpr const Stats* Find(uint64_t instance_id)
    {
        std::size_t lo = 0, hi = Table.size();

        while (lo < hi)
        {
            std::size_t mid = lo + (hi - lo) / 2;

            if (Table[mid].instance_id < instance_id)
            {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if (lo < Table.size() && Table[lo].instance_id == instance_id)
        {
            return Table[lo].data;
        }

        return nullptr;
    }

    constexpr const Stats* Find(std::string_view name)
    {
        for (const auto& entry : Table)
        {
            if (entry.name == name)
            {
                return entry.data;
            }
        }

        return nullptr;
    }
} // namespace Stats_Registry
} // namespace GDDL

#endif // GDDL_GENERATED_H
