// Auto-generated by the GDDL compiler. Do not edit by hand.

#include "generated_indexed_split_soa.h"

namespace GDDL
{

namespace Object_SoA
{
    const std::array<uint32_t, 6> something1 = { 0, 100, 5, 10, 1, 10 };

    const std::array<uint32_t, 6> something2 = { 0, 50, 50, 20, 2, 2 };
} // namespace Object_SoA

namespace Object_SoA_Registry
{
    const std::array<Entry, 6> Table =
    {
        Entry{ 0x4e4417bdfce7a91aULL, "HeavyObject", 1 },
        Entry{ 0xad84053e592e7248ULL, "DefaultObject", 0 },
        Entry{ 0xea3fb911673e5dc9ULL, "LightObject", 2 },
        Entry{ 0xed9105d6ab5f2814ULL, "RealObjectGen1", 4 },
        Entry{ 0xed9108d6ab5f2d2dULL, "RealObjectGen2", 5 },
        Entry{ 0xf334fa27c5ce1648ULL, "BaseObject", 3 },
    };

    std::size_t Find(uint64_t instance_id)
    {
        std::size_t lo = 0, hi = Table.size();

        while (lo < hi)
        {
            std::size_t mid = lo + (hi - lo) / 2;

            if (Table[mid].instance_id < instance_id)
            {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if (lo < Table.size() && Table[lo].instance_id == instance_id)
        {
            return Table[lo].row;
        }

        return Table.size();
    }

    std::size_t Find(std::string_view name)
    {
        for (const auto& entry : Table)
        {
            if (entry.name == name)
            {
                return entry.row;
            }
        }

        return Table.size();
    }
} // namespace Object_SoA_Registry

namespace Item_SoA
{
    const std::array<uint32_t, 3> object_something1 = { 10, 99, 10 };

    const std::array<uint32_t, 3> object_something2 = { 20, 100, 20 };

    const std::array<uint32_t, 3> weight = { 5, 7, 50 };

    const std::array<Element, 3> element = { Element::fire, Element::ice, Element::lightning };

    const std::array<char, 48> name =
    {
        'S', 'w', 'o', 'r', 'd', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', '\0', 'S', 'h', 'i', 'e', 'l', 'd', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0'
    };

    const std::array<ActionAttack_Indexed, 3> fast_dispatch = { ActionAttack_Indexed::melee_weapon, ActionAttack_Indexed::ranged_weapon, ActionAttack_Indexed::melee_weapon };
} // namespace Item_SoA

namespace Item_SoA_Registry
{
    const std::array<Entry, 3> Table =
    {
        Entry{ 0x8ad19844df88b655ULL, "ItemViaBareModify", 1 },
        Entry{ 0xb1ea277c9f6610e8ULL, "ItemCopy", 2 },
        Entry{ 0xf1112704e607b426ULL, "ItemViaFullReplace", 0 },
    };

    std::size_t Find(uint64_t instance_id)
    {
        std::size_t lo = 0, hi = Table.size();

        while (lo < hi)
        {
            std::size_t mid = lo + (hi - lo) / 2;

            if (Table[mid].instance_id < instance_id)
            {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if (lo < Table.size() && Table[lo].instance_id == instance_id)
        {
            return Table[lo].row;
        }

        return Table.size();
    }

    std::size_t Find(std::string_view name)
    {
        for (const auto& entry : Table)
        {
            if (entry.name == name)
            {
                return entry.row;
            }
        }

        return Table.size();
    }
} // namespace Item_SoA_Registry
} // namespace GDDL
