#ifndef GDDL_GENERATED_H
#define GDDL_GENERATED_H

// Auto-generated by the GDDL compiler. Do not edit by hand.

#include <cstdint>
#include <array>
#include <string_view>

namespace GDDL
{

enum class ActionAttack : uint64_t
{
    melee_weapon = 0x5c96a731d7d47e03ULL,
    ranged_weapon = 0xaa92e2b5323e5154ULL,
};

enum class ActionAttack_Indexed : uint8_t
{
    melee_weapon = 0,
    ranged_weapon = 1,
};

enum class Element : uint64_t
{
    fire = 0x9bcf40f6874d9103ULL,
    ice = 0x8304148e0f4f19acULL,
    lightning = 0x2ac1c587b5474f2dULL,
    poison = 0xfa09e3b805721ebfULL,
};

namespace Object_SoA
{
    extern const std::array<uint32_t, 6> something1;
    extern const std::array<uint32_t, 6> something2;
}

namespace Object_SoA_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        std::size_t row;
    };

    extern const std::array<Entry, 6> Table;

    std::size_t Find(uint64_t instance_id);

    std::size_t Find(std::string_view name);
} // namespace Object_SoA_Registry

namespace Item_SoA
{
    extern const std::array<uint32_t, 3> object_something1;
    extern const std::array<uint32_t, 3> object_something2;
    extern const std::array<uint32_t, 3> weight;
    extern const std::array<Element, 3> element;
    extern const std::array<char, 48> name;
    extern const std::array<ActionAttack_Indexed, 3> fast_dispatch;
}

namespace Item_SoA_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        std::size_t row;
    };

    extern const std::array<Entry, 3> Table;

    std::size_t Find(uint64_t instance_id);

    std::size_t Find(std::string_view name);
} // namespace Item_SoA_Registry
} // namespace GDDL

#endif // GDDL_GENERATED_H
