#ifndef GDDL_GENERATED_H
#define GDDL_GENERATED_H

// Auto-generated by the GDDL compiler. Do not edit by hand.

#include <cstdint>
#include <array>
#include <string_view>

namespace GDDL
{

enum class ActionAttack : uint64_t
{
    melee_weapon = 0x5c96a731d7d47e03ULL,
    ranged_weapon = 0xaa92e2b5323e5154ULL,
};

enum class ActionAttack_Indexed : uint8_t
{
    melee_weapon = 0,
    ranged_weapon = 1,
};

enum class Element : uint64_t
{
    fire = 0x9bcf40f6874d9103ULL,
    ice = 0x8304148e0f4f19acULL,
    lightning = 0x2ac1c587b5474f2dULL,
    poison = 0xfa09e3b805721ebfULL,
};

struct Object
{
    uint32_t something1;
    uint32_t something2;
};

struct Item
{
    Object object;
    uint32_t weight;
    Element element;
    char name[16];
    ActionAttack_Indexed fast_dispatch;
};

namespace Object_Instances
{
    extern const Object DefaultObject;
    extern const Object HeavyObject;
    extern const Object LightObject;
    extern const Object BaseObject;
    extern const Object RealObjectGen1;
    extern const Object RealObjectGen2;
}

namespace Object_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        const Object* data;
    };

    extern const std::array<Entry, 6> Table;

    const Object* Find(uint64_t instance_id);

    const Object* Find(std::string_view name);
} // namespace Object_Registry

namespace Item_Instances
{
    extern const Item ItemViaFullReplace;
    extern const Item ItemViaBareModify;
    extern const Item ItemCopy;
}

namespace Item_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        const Item* data;
    };

    extern const std::array<Entry, 3> Table;

    const Item* Find(uint64_t instance_id);

    const Item* Find(std::string_view name);
} // namespace Item_Registry
} // namespace GDDL

#endif // GDDL_GENERATED_H
