#ifndef GDDL_GENERATED_H
#define GDDL_GENERATED_H

// Auto-generated by the GDDL compiler. Do not edit by hand.

#include <cstdint>
#include <array>
#include <string_view>

namespace GDDL
{

struct Stats
{
    uint16_t hp;
    uint16_t mp;
};

struct Equipment
{
    uint16_t weapon_power;
};

struct Character
{
    Stats stats;
    Equipment equipment;
    uint16_t level;
};

namespace Stats_Instances
{
}

namespace Stats_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        const Stats* data;
    };

    inline constexpr std::array<Entry, 0> Table = {};

    constexpr const Stats* Find(uint64_t instance_id)
    {
        std::size_t lo = 0, hi = Table.size();

        while (lo < hi)
        {
            std::size_t mid = lo + (hi - lo) / 2;

            if (Table[mid].instance_id < instance_id)
            {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if (lo < Table.size() && Table[lo].instance_id == instance_id)
        {
            return Table[lo].data;
        }

        return nullptr;
    }

    constexpr const Stats* Find(std::string_view name)
    {
        for (const auto& entry : Table)
        {
            if (entry.name == name)
            {
                return entry.data;
            }
        }

        return nullptr;
    }
} // namespace Stats_Registry

namespace Equipment_Instances
{
}

namespace Equipment_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        const Equipment* data;
    };

    inline constexpr std::array<Entry, 0> Table = {};

    constexpr const Equipment* Find(uint64_t instance_id)
    {
        std::size_t lo = 0, hi = Table.size();

        while (lo < hi)
        {
            std::size_t mid = lo + (hi - lo) / 2;

            if (Table[mid].instance_id < instance_id)
            {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if (lo < Table.size() && Table[lo].instance_id == instance_id)
        {
            return Table[lo].data;
        }

        return nullptr;
    }

    constexpr const Equipment* Find(std::string_view name)
    {
        for (const auto& entry : Table)
        {
            if (entry.name == name)
            {
                return entry.data;
            }
        }

        return nullptr;
    }
} // namespace Equipment_Registry

namespace Character_Instances
{
    inline constexpr Character Hero = { Stats{ 60000, 12000 }, Equipment{ 500 }, 42 };
}

namespace Character_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        const Character* data;
    };

    inline constexpr std::array<Entry, 1> Table =
    {
        Entry{ 0x5ff2940d2286ca5cULL, "Hero", &Character_Instances::Hero },
    };

    constexpr const Character* Find(uint64_t instance_id)
    {
        std::size_t lo = 0, hi = Table.size();

        while (lo < hi)
        {
            std::size_t mid = lo + (hi - lo) / 2;

            if (Table[mid].instance_id < instance_id)
            {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if (lo < Table.size() && Table[lo].instance_id == instance_id)
        {
            return Table[lo].data;
        }

        return nullptr;
    }

    constexpr const Character* Find(std::string_view name)
    {
        for (const auto& entry : Table)
        {
            if (entry.name == name)
            {
                return entry.data;
            }
        }

        return nullptr;
    }
} // namespace Character_Registry
} // namespace GDDL

#endif // GDDL_GENERATED_H
