#ifndef GDDL_GENERATED_H
#define GDDL_GENERATED_H

// Auto-generated by the GDDL compiler. Do not edit by hand.

#include <cstdint>
#include <array>
#include <string_view>

namespace GDDL
{

namespace Enemy_SoA
{
    inline constexpr std::array<std::array<int32_t, 2>, 2> damage_min_max = {{ { 10, 30 }, { 10, 80 } }};

    inline constexpr std::array<std::array<std::array<int32_t, 3>, 2>, 2> grid = {{ {{ { 1, 2, 3 }, { 4, 5, 6 } }}, {{ { 1, 2, 3 }, { 4, 5, 6 } }} }};

    inline constexpr std::array<std::array<std::array<char, 16>, 4>, 2> names = {{ {{ { "Alice" }, { "Bob" }, { "Carol, Jr." }, { "Dave" } }}, {{ { "Alice" }, { "Bob" }, { "Carol, Jr." }, { "Dave" } }} }};
}

namespace Enemy_SoA_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        std::size_t row;
    };

    inline constexpr std::array<Entry, 2> Table =
    {
        Entry{ 0x3a8e66ab429d7ffcULL, "StrongerGoblin", 1 },
        Entry{ 0x4ee3563a6adda595ULL, "BaseGoblin", 0 },
    };

    constexpr std::size_t Find(uint64_t instance_id)
    {
        std::size_t lo = 0, hi = Table.size();

        while (lo < hi)
        {
            std::size_t mid = lo + (hi - lo) / 2;

            if (Table[mid].instance_id < instance_id)
            {
                lo = mid + 1;
            } else {
                hi = mid;
            }
        }

        if (lo < Table.size() && Table[lo].instance_id == instance_id)
        {
            return Table[lo].row;
        }

        return static_cast<std::size_t>(-1);
    }

    constexpr std::size_t Find(std::string_view name)
    {
        for (const auto& entry : Table)
        {
            if (entry.name == name)
            {
                return entry.row;
            }
        }

        return static_cast<std::size_t>(-1);
    }
} // namespace Enemy_SoA_Registry

// §17.5: compile-time schema table, for comparison against
// whatever a loaded .gddldata.bin/.gddlmeta.json pair claims at
// runtime (§17.6). schema_hash/record_size here are computed by
// the EXACT SAME functions the .gddldata.bin exporter calls --
// see export_cpp.py's compute_schema_hash/compute_record_size,
// shared with export_binary.py, never a second implementation.
struct SchemaEntry
{
    std::string_view type_name;
    uint64_t schema_hash;
    uint32_t record_size;
};

inline constexpr std::array<SchemaEntry, 1> SchemaTable =
{
    SchemaEntry{ "Enemy", 0x86fcd4cb436de7daULL, 96 },
};

} // namespace GDDL

#endif // GDDL_GENERATED_H
