#ifndef GDDL_GENERATED_H
#define GDDL_GENERATED_H

// Auto-generated by the GDDL compiler. Do not edit by hand.

#include <cstdint>
#include <array>
#include <string_view>

namespace GDDL
{

enum class ActionAttack : uint64_t
{
    melee_weapon  = 0x5c96a731d7d47e03ULL, // Standard attack done with a melee weapon
    ranged_weapon = 0xaa92e2b5323e5154ULL, // Standard attack done with a ranged weapon
};

enum class ActionAttack_Indexed : uint8_t
{
    melee_weapon  = 0, // Standard attack done with a melee weapon
    ranged_weapon = 1, // Standard attack done with a ranged weapon
};

enum class Element : uint64_t
{
    fire      = 0x9bcf40f6874d9103ULL, // Elemental fire damage type
    ice       = 0x8304148e0f4f19acULL, // Elemental ice damage type
    lightning = 0x2ac1c587b5474f2dULL, // Elemental lightning damage type
    poison    = 0xfa09e3b805721ebfULL, // Elemental poison damage type
};

struct Object
{
    uint32_t something1;
    uint32_t something2;
};

struct Item
{
    Object               object;
    uint32_t             weight;
    Element              element;
    char                 name[16];
    ActionAttack_Indexed fast_dispatch;
};

namespace Object_Instances
{
    extern const Object DefaultObject;
    extern const Object HeavyObject;
    extern const Object LightObject;
    extern const Object BaseObject;
    extern const Object RealObjectGen1;
    extern const Object RealObjectGen2;
}

namespace Object_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        const Object* data;
    };

    extern const std::array<Entry, 6> Table;

    const Object* Find(uint64_t instance_id);

    const Object* Find(std::string_view name);
} // namespace Object_Registry

namespace Item_Instances
{
    extern const Item ItemViaFullReplace;
    extern const Item ItemViaBareModify;
    extern const Item ItemCopy;
}

namespace Item_Registry
{
    struct Entry
    {
        uint64_t instance_id;
        std::string_view name;
        const Item* data;
    };

    extern const std::array<Entry, 3> Table;

    const Item* Find(uint64_t instance_id);

    const Item* Find(std::string_view name);
} // namespace Item_Registry

// §17.5: compile-time schema table, for comparison against
// whatever a loaded .gddldata.bin/.gddlmeta.json pair claims at
// runtime (§17.6). schema_hash/record_size here are computed by
// the EXACT SAME functions the .gddldata.bin exporter calls --
// see export_cpp.py's compute_schema_hash/compute_record_size,
// shared with export_binary.py, never a second implementation.
struct SchemaEntry
{
    std::string_view type_name;
    uint64_t schema_hash;
    uint32_t record_size;
};

inline constexpr std::array<SchemaEntry, 2> SchemaTable =
{
    SchemaEntry{ "Object", 0xc3b65b8d9dc943b8ULL, 8 },
    SchemaEntry{ "Item", 0x2c99385395d2d57eULL, 37 },
};

} // namespace GDDL

#endif // GDDL_GENERATED_H
