/* Auto-generated by the GDDL compiler (Z80 / z88dk C mode). Do not edit by hand. */
/* Header: declarations only -- C89, targeting zsdcc. Compile with: zcc +<target> -compiler=sdcc ... */
/* --z80-pointer-table=on (SPEC S16.2) */

#ifndef GDDL_Z80_EXPORT_H
#define GDDL_Z80_EXPORT_H

/* --- type: Character (AoS, sizeof == 8) --- */
typedef struct {
    unsigned int stats_hp;
    unsigned int stats_mp;
    unsigned int equipment_weapon_power;
    unsigned int level;
} Character;

#define Character_Registry_Count 1
#define Character_Hero_Index 0

extern const Character Character_Instances[Character_Registry_Count];
extern const Character *const Character_Registry[Character_Registry_Count];
const Character *Character_Find(unsigned char index);

#endif /* GDDL_Z80_EXPORT_H */
